### ISSUE TITLE
secrets: Documentation and Implementation mismatch

### ISSUE THREAD

**Issue by noc0lour** [buildbot/buildbot#3130]
I'm trying to use the secrets provider to supply tokens. Unfortunately docs and implementation have are different. I just used the `SecretIn(A)File` provider.

 - Class names are not the same
 - Parameter names are not the same.
 - Class is missing in `util` (setup.py entries missing)

**Comment by tardyp** [comment]
+ @protatremy

**Comment by Lekensteyn** [comment]
Wouldn't `SecretsDirectory` be an even better name? Effectively you have a directory containing secrets (in files).

"SecretsInFile" sounds like a passwd(5)-like file (suggested in #3178).

**Comment by protatremy** [comment]
I purpose to start correcting all mismatches between the documentation and the code and I let you change the name if you want.

**Comment by Lekensteyn** [comment]
So now the class and parameter names are consistent (well, except for the tests which are still called TestSecretInFile.testSecretInFileXxx), I'll wait for #3194 to be processed and then rename the classes to `SecretsDirectory` and add a corresponding entry in util.

Since the name was missing in util and the documentation was incorrect, are you OK with renaming it in 0.9.8 as-is without backwards compatibility considerations?

**Comment by tardyp** [comment]
it is SecretInAFile, not SecretsInAFile. passwd(5) would be SecretsInDotPasswd

SecretsDirectory does not hint on how the secrets are stored imho.
