### ISSUE TITLE
Missing owner value on builder buildtable

### ISSUE THREAD

**Issue by pmisik** [buildbot/buildbot#3311]
On builders build table there is a column Owner which is empty even if builder has valid property owner. 

This is probably due to no value is supplied.
https://github.com/buildbot/buildbot/blob/master/www/base/src/app/common/directives/builds/buildstable.tpl.jade#L27
I don’t know how this work so I tried to add 

`{{ build.owner }}`
or
```
span(title="{{build.owner}}")
              | {{ build.owner }}
```
But it did not work. 
I would also appreciate to have reason from build properties in that table. It would increase usability in use case you use BB for creating custom builds and later you search for you build in order to run rebuild.

**Comment by tardyp** [comment]
Indeed, build.owner is not part of data api. https://github.com/buildbot/buildbot/blob/master/master/buildbot/spec/types/build.raml#L22

The build table needs to fetch additional 'owner' property in order to make it work
similar to what is done in console view:
https://github.com/buildbot/buildbot/blob/master/www/console_view/src/module/main.module.coffee#L80

I would be very happy if you can work on it!

**Comment by krf** [comment]
Can be closed since https://github.com/buildbot/buildbot/pull/3951 is in?
