### ISSUE TITLE
Deprecated status classes should log error/warning message about them being deprecated

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3441]
In buildbot 0.9 all the status classes are deprecated. However, previous classes still work but with limited functionality.

For e.g. base.StatusReceiverMultiService works but with limited functionality. Further, there is no mention in documentation about all the classes which are deprecated. Searching about StatusReceiverMultiService in buildbot documentation gives no results. This results in a very frustrating experience while trying to upgrade from 0.8 to 0.9.

All the deprecated classes should print an error/warning message about them being deprecated and suggest using reporter API instead.

**Comment by tardyp** [comment]
I would rather spend time removing them completely rather than adding some deprecation warnings. I think this paragraph is already clear enough:

http://docs.buildbot.net/latest/manual/installation/nine-upgrade.html#status-classes

please don't hesitate to submit a PR to change the wording, to make it a clearer if you think it is not.

I believe there are lots of issues that are frustrating when upgrading to nine, and those will be different depending on the level of customization ppl have.

People should read the upgrading guide carefully to avoid that frustration as much as possible.

**Comment by p12tic** [comment]
All status-related things have been marked as deprecated in 2.10 and will be removed in 3.0.
