### ISSUE TITLE
elapsed time for current build is negative

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3457]
Frequently, while loading webpages, buildbot shows negative time for time elapsed for current build/step. It gets corrected automatically after few seconds. However, if buildbot is not very fast, this is very noticeable. Seems like some script taking long time to load and displaying negative time meanwhile.

Few screenshots below.

<img width="290" alt="screen shot 2017-07-20 at 6 47 57 pm" src="https://user-images.githubusercontent.com/3098702/28449022-5b899822-6d91-11e7-9c97-8d5bd959e631.png">

<img width="1262" alt="screen shot 2017-07-20 at 9 20 18 pm" src="https://user-images.githubusercontent.com/3098702/28449026-5e92a176-6d91-11e7-82d5-360c7fb7d2fa.png">

**Comment by tardyp** [comment]
That is probably an easy fix. Any help appreciated!

**Comment by aakashja** [comment]
This seems to happen when the time on server is different than the time on client. In my case time on server was somehow ~30s ahead of actual time (probably some misconfiguration).

Nevertheless, buildbot should not display negative time.

**Comment by Frodox** [comment]
@aakashja do you mean server == bb-master host, client == user, who open web-page ?

**Comment by aakashja** [comment]
@Frodox yes

**Comment by vadini-agrawal** [comment]
Taking a look at where this might be happening, does it sound right that it's happening because of this line? https://github.com/buildbot/buildbot/blob/d5616a3b9fa17108b767c32806ca916923094835/master/buildbot/statistics/capture.py#L286 
Either this could be solved by setting the min duration to 0, or by getting different start/end time values somewhere else?
