### ISSUE TITLE
What's the meaning of the Changes Tab？

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3468]
Only the newest change triggered the build, but the `Changes` Tab contains many changes. How does the framework determine these changes?
![image](https://user-images.githubusercontent.com/19603852/28513823-34913580-708a-11e7-95bd-5b8318ae94c7.png)

**Comment by lancelodliu** [comment]
It seems that this Tab is generated based on result of `self.master.data.get(("builds", build['buildid'], "changes"))`. The question is why does the result contain a lot unrelevant old changes **sometimes**?

**Comment by tardyp** [comment]
Hi.
This request returns the changes that came since the last successful build.
In case of a traditional post commit build, this means that all those
changes may be responsible for a failure since we don't have face of
success in between.

This is not always meaningful especially for precommit use case, where
changes are sent usually to the same builder, not particularly ordered.
I am not sure how to make buildbot handle better the two use cases and
probably other I can't think of.

Maybe we should label it better in the ui as a first step. Would you like
to submit a PR for it?

Le mer. 26 juil. 2017 05:54, lancelodliu <notifications@github.com> a
écrit :

**Comment by lancelodliu** [comment]
So the command `self.master.data.get(("builds", build['buildid'], "changes"))` returns the same result as you explained: 
> the changes that came since the last successful build

**Comment by tardyp** [comment]
Right. this could be indeed better documented in the raml spec. http://docs.buildbot.net/latest/developer/rest.html#id10

> This path selects all changes tested by a build

I guess this reserves us the right to change the algorithm to find a better one.

**Comment by lancelodliu** [comment]
@tardyp Then is there a way to determine the change which triggered this build?

**Comment by tardyp** [comment]
Yes. It is the one that has the same ssid as the one present in the buildset

Le mer. 26 juil. 2017 09:39, lancelodliu <notifications@github.com> a
écrit :

**Comment by lancelodliu** [comment]
Thanks. But that makes it difficult to send mail to the author whose commit triggered the build because the `MailNotifier` use `utils.getResponsibleUsersForBuild` to get the user list.
