### ISSUE TITLE
steps endpoint in REST API doesn't have urls information 

### ISSUE THREAD

**Issue by aakashja** [buildbot/buildbot#3529]
In buildbot 0.9, steps endpoint REST API doesn't have urls information.
e.g. https://nine.buildbot.net/api/v2/builders/9/builds/1017/steps 

In the output all the steps have empty list for urls:  _"urls": []_

In buildbot 0.8, rest api used to correctly return the url for every step (in "logs").

Sample output:
```
{
      "buildid": 155820, 
      "complete": true, 
      "complete_at": 1502826434, 
      "hidden": false, 
      "name": "git-buildbot", 
      "number": 0, 
      "results": 0, 
      "started_at": 1502826423, 
      "state_string": "update buildbot", 
      "stepid": 657946, 
      "urls": []
    }, 
    {
      "buildid": 155820, 
      "complete": true, 
      "complete_at": 1502826434, 
      "hidden": false, 
      "name": "setup-steps", 
      "number": 1, 
      "results": 0, 
      "started_at": 1502826434, 
      "state_string": "finished", 
      "stepid": 657985, 
      "urls": []
    }
```

**Comment by tardyp** [comment]
Hi @aakashja 
Buildbot eight API wrongly merged URLs and log URLs.
In buildbot nine, there is a difference, and the steps only contain the URLs that one could put in custom steps with self.addUrl() or in DownloadSteps.

e.g. https://nine.buildbot.net/api/v2/builders/9/builds/1017/steps/2/logs
and to access content:
https://nine.buildbot.net/api/v2/builders/9/builds/1017/steps/2/logs//stdio/content
https://nine.buildbot.net/api/v2/builders/9/builds/1017/steps/2/logs/stdio/raw


In order to access logs, you need to use the logs endpoint
