### ISSUE TITLE
ForceScheduler collapse tasks

### ISSUE THREAD

**Issue by pohmelie** [buildbot/buildbot#3566]
I have force scheduler with properties:
``` python
properties=[
    util.StringParameter(
        name="targets",
        label="Targets (see packages.yml):",
        required=True,
    ),
],
```
When I force many tasks, so they should be queued. But only one (last one) stays in queue and queue size is always 1.

**Comment by pohmelie** [comment]
Actually buildrequests stay in db, but did not actually started.

**Comment by lancelodliu** [comment]
try `collapseRequests=False` in the `util.BuilderConfig`

**Comment by pohmelie** [comment]
@lancelodliu 
Thank you! It works!

**Comment by Frodox** [comment]
This is because they compared by codebase (revision, branch, repository, project), which is same in you case. So, if you want to compare by some custom property, you can 
* disable collapseRequests at all
* [write custom function for collapsing](http://docs.buildbot.net/latest/manual/customization.html#collapse-request-functions) (preferable way, depends on your goal)

**Comment by pohmelie** [comment]
@Frodox 
Thanks, I'm fine with disable `collapseRequests`.
