### ISSUE TITLE
database error duplicate key value violates unique constraint scheduler_masters_pkey

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#3665]
I looked at postgres logs and noticed a lot of errors like this:

```
< 2017-09-29 13:19:48.822 PDT > ERROR:  duplicate key value violates unique constraint "scheduler_masters_pkey"
< 2017-09-29 13:19:48.822 PDT > DETAIL:  Key (schedulerid)=(338) already exists. 
< 2017-09-29 13:19:48.822 PDT > STATEMENT:  INSERT INTO scheduler_masters (schedulerid, masterid) VALUES (338, 2)
```

```
buildbot=# select * from scheduler_masters where schedulerid=338;
 schedulerid | masterid
 -------------+----------
         338 |        1
```

I am using a simple multi-master setup with 2 masters. One handling UI (and having schedulers information as well) and other handling everything else. masterid 1 is web-server and 2 is back-end.

Are both the masters trying to insert the same buildrequest into database? Can it be issue in multi-master configuration and both master having similar configuration (both have schedulers information in master.cfg)?

**Comment by tardyp** [comment]
errors in pg logs are not meaning ful. There are several usecase where buildbot purposely try to insert duplicates in order to deal with race conditions
We properly filter out those db errors from twisted.log

In this case, the two masters are fighting for the scheduler. Only one is winning. This is the strategy that is used for "master election".
