### ISSUE TITLE
Update existing change feature

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#3701]
Sometimes, it is convenient to re-send a change to the server to "rebuild" a set of builds. The reason behind that can be:

* There was an infrastructure problem and we need to run everything again.
* We need to rebuild the same revision but with different change properties

For now, when doing that, a new change is created but linked to the same sourcestampid than the old change. And builds are re-scheduled but linked to the old change (so new properties are ignored).

It would be better to update the existing change with the new properties and re-trigger schedulers with the same changes/sourcestamp.

**Comment by Hyask** [comment]
Just for the record, after some discussions with @rjarry.

A hack can be done to fix the problem there:
https://github.com/buildbot/buildbot/blob/02d8fe20aee02788281042733a24b4d11486ab24/master/buildbot/db/changes.py#L222 
Just append `.order_by(changes_tbl.c.changeid.desc())` to the query, so that the last change corresponding the to the asked sourcestampid is fetched, rather than the first.

This works, at least in my personal simple case, but will likely never get upstream, since this is just a hack, and a better solution should be found.
