### ISSUE TITLE
SVN buildstep -- need help with a standard use-case

### ISSUE THREAD

**Issue by jdpipe** [buildbot/buildbot#3728]
Current documentation does not make it clear how to use `SVN` `BuildStep` with multiple branches, including trunk.
So if my branch is named 'branch1', how can I configure the web user interface to allow a `ForceScheduler` with a choice between 'trunk' and 'branch1'? It seems that I have to use `util.Interpolate`, but if `branch`='trunk' then I need the URL to be `http://svn.myproj.org/trunk` but if branch has any other value, then I need the URL to be `http://svn.myproj.org/branches/mybranchname`. This turns out to be non-trival to implement with `util.Interpolate` and used to work perfectly with a `branch` kwarg. It would be very helpful to provide a helper function for the standard case of a SVN repo, perhaps?

**Comment by jdpipe** [comment]
My rather clunky workaround is as follows. Would be keen to know if someone has a nicer alternative (and it would be cool to see something like this referenced in the docs)

```
ASCEND_SVN = "http://svn.ascend4.org/"

def SVNURL(branch):
    if branch is "trunk":
        return "%s%s" % (ASCEND_SVN,"trunk")
    else:
        return "%sbranches/%s" % (ASCEND_SVN,urllib.parse.quote_plus(branch))

ASCEND_SVN_INTERP = util.Transform(SVNURL,util.Interpolate("%(src::branch)s"))
```

**Comment by tardyp** [comment]
Looking at the source code at https://github.com/buildbot/buildbot/blob/master/master/buildbot/steps/source/svn.py#L76

It looks like the current svn code for Buildbot does not account for branch parameter.

Looking at the doc, it looks like you are supposed to use interpolate of repo url in order to account for branch. I don't think this can work with codebase also.

From what I remember of svn, I think the branch namings where rather conventional and not mandatory, nothing forces you to use trunk as the main branch, and branches/branch as subsequent branches.
You are welcome to improve the doc, and put your code in the documentation as the official way ( I don't think it is a ugly workaround btw. what is ugly for me is the svn convention being different for trunk)

**Comment by jdpipe** [comment]
Buildbot used to support this stuff natively, eg see the fact that the 'trunk' branch was built-in in the SVN class in the past (`defaultBranch` in https://github.com/buildbot/buildbot/commit/a31ef36617071d13b901c92bcba6bc2db996b331). The `branch` parameter still exists in the `Source` class, so it seems that this feature was impartially removed. Perhaps it could be restored.

**Comment by lancelodliu** [comment]
I make branch name to be `branches/mybranchname` as a workaround and avoid to use `@util.renderer`.

**Comment by jdpipe** [comment]
There's some logic to that... it means that 'tags' (eg for released versions, etc) can also be used as the basis for builds. Whatever is used, it has to flow through to the contribs/.../svn_buildbot.py script since that is where the branch associated with a commit needs to be identified (as far as I understand it).
