### ISSUE TITLE
Debian packaging discussions

### ISSUE THREAD

**Issue by tardyp** [buildbot/buildbot#3809]
followup on the packaging discussions happening on #3804

**Comment by tardyp** [comment]
@simevo

> The plan is to redo your build process on debian infrastructure and with debianized tooling, starting from the github tarball as source (not the "output" tarball that you produce which for us is a "binary" artifact)

I am not sure which plan you are referring. Are you planning to be the debian maintainer for us?

We currently have other discussions with debian folks about doing this:
```
From: Matthias Klose <doko@debian.org>
To: Robin Jarry <robin.jarry@6wind.com>, jolly_roger@itblog.org.ua, "W. Martin Borgert" <debacle@debian.org>
Subject: Re: Buildbot debian packaging

On 14.11.2017 15:51, Robin Jarry wrote:
> Hi fellows,
>
> I noticed that the debian packaged version of buildbot and
> buildbot-slave is still on the 0.8.x branch.
>
> A new 0.9.x version is available since october 2016 and I really think
> it would be a good thing to upgrade the debian package to a more recent
> version. Here are some links to the new web dashboard:
>
> https://nine.buildbot.net/
> https://nine.buildbot.net/#/console
> https://nine.buildbot.net/#/grid
> https://nine.buildbot.net/#/waterfall
>
> Please note that this new version changes a lot of things and the
> upgrade procedure can be tricky.
>
> https://docs.buildbot.net/current/manual/installation/nine-upgrade.html
>
> Let me know if there is something I can do to help.

Hi,

I just filed #883529 to orphan the packages. I didn't get any feedback from
Andrij since July 2016, and feedback from before that date was scarce as well.
Please feel free to adopt the packages, and coordinate maybe with Martin about
sponsoring/co-maintaining the packages.  I'm available for initial uploads as
well, but won't have the time to maintain these packages. And buildbot-0.9.x
should use Python3 from the start ...

Matthias

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883529
```
We discussed it during our weekly meeting yesterday, and @rjarry was candidating to be the debian downstream maintainer for us.

There is few chance that we can remove guanlecoja/buildbot-pkg build system in a reasonable timeframe. 
I would like we can work on a solution to integrate into debian without reworking that.
We are already packaged into gentoo, nix and freebsd (AFAIK, they are using the pypi tarballs)

I am not sure what is the current debian tooling on building nodejs applications.
Also note that nodejs is only a build dependency to buildbot-www not a runtime dependency.

**Comment by simevo** [comment]
Sorry I wasn't clear enough. "_The plan ... to redo your build process on debian infrastructure and with debianized tooling, starting from the github tarball as source_" is the plan the maintainer of the now-orphaned buildbot package **will have** to follow, whoever will take on that role, because that's the only plan compatible with debian rules.

@rjarry is welcome to step in and be the maintainer !

There is also the option of **team maintenance**. buildbot has both python and JavaScript/coffescript stuff, but it is essentially a python application so it could be co-maintained in the [Python Applications Packaging Team (**PAPT**)](https://wiki.debian.org/Teams/PythonAppsPackagingTeam).

As to myself, I have been in touch with **jolly_roger** and **debacle** in the past because I have an interest in keeping buildbot in debian, but I have not volunteered myself to maintain it because it's a bit too much for my debian python packaging skills.

Let me quote here a few points that **jolly_roger** raised about [a year ago](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790241#52):

> - in addition to the "buildbot" and "buildbot-worker" Python packages upstream now ships its web interface in the separate package called "buildbot-www" that is built into standard Python module with nodejs and friends;
> - "buildbot-www" also has modular architecture and provides some plugins out of the box;
> - additional plugins can be developed using package called "buildbot-pkg" that is available in the upstream repository as well.

I am more involved in the [Debian JavaScript Maintainers Team (**pkg-javascript**)](https://wiki.debian.org/Javascript) and I'll be happy to help you on buildbot-www.

The current status of debian tooling for building nodejs stuff for the browser is exemplified in a WIP package I am working on ATM, **vue.js**, which is built with webpack+babel.
The `debian/rules` file is a disguised `Makefile` interspersed with [debhelper wizardry](http://manpages.ubuntu.com/manpages/wily/man1/dh_auto_build.1.html); custom build steps are normally added to the `override_dh_auto_build` target, in this case during the build `webpack` is invoked:
https://anonscm.debian.org/git/pkg-javascript/vue.js.git/tree/debian/rules#n12
So webpack is a build-dependency, listed in the `debian/control` file:
https://anonscm.debian.org/git/pkg-javascript/vue.js.git/tree/debian/control#n10
We have to supply a webpack config (here upstream uses a different build tool, rollup, which is not yet been debianized):
https://anonscm.debian.org/git/pkg-javascript/vue.js.git/tree/debian/webpack.config.js
and we tweak the upstream `.babelrc` to our needs with a patch:
https://anonscm.debian.org/git/pkg-javascript/vue.js.git/tree/debian/patches/02-babelrc.diff

Note that all this is located in the `debian` directory, which we add after untarring the upstream tarball.
In pkg-javascript team we use git and the [git-buildpackage](http://honk.sigxcpu.org/projects/git-buildpackage/manual-html/gbp.html) tool, whereby the upstream tarball is mirrored in our git repo's `upstream` branch:
https://anonscm.debian.org/git/pkg-javascript/vue.js.git/log/?h=upstream
and the `debian` directory is only added to the `master` branch.

For python teams, the matter is a bit different. The PAPT team still uses SVN (!) whereas the other one, the Debian Python Modules Team (**DPMT**), has a policy to use [git-dpm](https://wiki.debian.org/PackagingWithGit/GitDpm) tool, but if I understand correctly they are transitioning to [git-buildpackage and gbp-pq](https://wiki.debian.org/Python/GitPackagingPQ).

**Comment by tardyp** [comment]
adding @jollyroger  to the discussion.

I am not sure it is a good idea to change upstream's build method, and I am sad that this will certainly add a big delay in having buildbot packaged for debian.

I was sure I've seen grafana being packaged in debian out of pre-built javascript. It looks like it is not the case anymore.

```yarn list |wc -l```
Gives me 1319 npm packages to do in order to properly package guanlecoja. Not to mention that there are lots of duplicates there with different versions. As much as I think this is crazy. This is how npm ecosystem is working

I see from this page:
https://wiki.debian.org/Javascript/Nodejs/Tasks/webpack
That packaging big nodejs is actually possible, and I am amazed by the work you've done.
I am not sure how much this requires manual work, or if this is automatic, and we could run that for guanlecoja?


There is also the problem of packaging the front end dependencies.

guanlecoja do manage the list of dependencies so that we can display them on our about page:
https://nine.buildbot.net/#/about
I assume all those would have to be packaged as well.

**Comment by simevo** [comment]
For packaging nodejs modules we have a semi-automated process, the main tool is [npm2deb](https://wiki.debian.org/Javascript/Nodejs/Npm2Deb).

To get an idea about the work required to package gualencoja, I have created a task page for it similar to the webpack one you found:
https://wiki.debian.org/Javascript/Nodejs/Tasks/guanlecoja
Note that:
- it only finds 764 w.r.t. 1319 from 'yarn list` - not quite sure why
- when dependencues occur repeatedly ("duplicates") with different versions, in debian in general we would only have the latest version; in this respect the debian paradigm is incompatible with the npm ecosystem

Anyway looking at that, it's not too bad actually. Assuming that for debian purposes we can skip karma, it's about 20 dependencies + 19 build dependencies (all gulp-* stuff)

About front-end dependencies, this is my first pass:

name|version|debian package|debian version
---|---|---|---
jquery|2.2.3|https://packages.debian.org/sid/libjs-jquery|3.2.1
angular|1.5.3|https://packages.debian.org/sid/libjs-angularjs|1.5.10
angular-animate|1.5.3||
angular-bootstrap|1.1.2||
angular-ui-router|0.2.18||
angular-recursion|1.0.5||
lodash|4.11.1|https://packages.debian.org/sid/libjs-lodash|4.17.4
guanlecoja-ui|1.7.2||
moment|2.6.0|https://packages.debian.org/sid/libjs-moment|2.19.3
d3|3.4.13|https://packages.debian.org/sid/libjs-d3|3.5.17
font-awesome|4.1.0|https://packages.debian.org/sid/fonts-font-awesome|4.7.0
bootstrap|3.1.1|https://packages.debian.org/sid/libjs-bootstrap|3.3.7
buildbot-data|1.0.15||
angular-bootstrap-multiselect|1.1.11||
angular-bootstrap-show-errors|2.2.0||
ng-tags-input|3.0.0||
ace-builds|1.1.5||
angular-ui-ace|0.1.1||

one would than have to dig into each of the missing ones and do a task page as I did for gualencoja...

As you see for some front-end dependencies we're actually ahead of the buildbot project, and that can also be a source of trouble unless you also update to jquery 3, angular 1.5.10, bootstrap 3.3.7 ...

**Comment by dankegel** [comment]
Looking forward to hearing more about this.

**Comment by rjarry** [comment]
@simevo since we finally got rid of coffeescript and switched to webpack for building, I thought it would be a good time to consider packaging the www modules into debian.

I tried asking for help on #debian-js (on OFTC IRC server) without much replies.

The first blocking problem I have is that there are a lot of missing (or outdated) dependencies. Could you help (or know someone who can)?

**Comment by rjarry** [comment]
@simevo also, the buildbot debian packaging is now managed by PAPT and hosted on salsa: https://salsa.debian.org/python-team/applications/buildbot

I had forgotten that you proposed a co-maintenance with the JS team. That would certainly help a lot :)

**Comment by p12tic** [comment]
Seems like this issue can be closed, as most recent Buildbot is in Debian. We can open new issues for any new problems that arise.
