### ISSUE TITLE
Recent builds not showing in the "Builders" page

### ISSUE THREAD

**Issue by rjarry** [buildbot/buildbot#3820]
This happens when upgrading from 0.9.13 to 0.9.14.

![image](https://user-images.githubusercontent.com/472286/33898826-d902f754-df69-11e7-99b8-e6dc13a91e24.png)

**Comment by umar456** [comment]
I have also run into this issue. Also there are two Builds->Workers items on the left hand menu as shown in the image above.

**Comment by krzk** [comment]
Same in my case after upgrade (and running upgrade-master and cleanupdb). Clearing the MySQL database (dropping all tables) did not solve the issue. In the same time a fresh installation of 0.9.14 on different host (so slightly different Python, MariaDB instead of MySQL and few other differences) works fine.

**Comment by diegomarcov** [comment]
Same thing is happening to me using Buildbot 0.9.14. No builds showing at all.

**Comment by rayalan** [comment]
Same thing happened to me upgrading from 0.9.9p2 to 0.9.14 (running Maria and Python 2.7.5).

**Comment by tichy3000** [comment]
Hi, I upgraded from 0.9.14 to 1.1.1 and I'm still having no builds on the Builder page. Also there are still the two Builds->Worker items on the menu list.

Can you reproduce these problems and reopen the issue?
