### ISSUE TITLE
How to set build result in a build step?

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#3912]
I wanna set build result to `SKIPPED`. Is it possible?

**Comment by tardyp** [comment]
There are lots of options for that.

- Create a custom BuildStep which has its run() method return buildbot.process.results.SKIPPED
- Create a custom Shell step which has its evaluateCommand() return buildbot.process.results.SKIPPED (conditionally according to shell command results)

Note that if the current result of the build is exception or retry, the overall build result will stay exception or retry. The order of priority is:
SUCCESS, WARNINGS, FAILURE, SKIPPED, EXCEPTION, RETRY, CANCELLED 

In order to overridde this priority, you would need to hack and override the builds current results by doing following a step context:

```python
self.build.results = SKIPPED

```

**Comment by lancelodliu** [comment]
@tardyp I tried the first way and it doesn't work. Returning SKIPPED in run() method will mark the build as SUCCESS.
```python
class SetStepResult(BuildStep):
    name = 'SetStepResult'
    renderables = ['result']

    def __init__(self, result, **kwargs):
        self.result = result
        BuildStep.__init__(self, **kwargs)

    def run(self):
        return defer.succeed(self.result)
```
![image](https://user-images.githubusercontent.com/19603852/35373787-14d7eada-01db-11e8-8058-2ace48ac9a7c.png)
The hack way works actually.
![image](https://user-images.githubusercontent.com/19603852/35373832-47d791ba-01db-11e8-828e-e7289a5830f4.png)

I am using version 0.9.11.
