### ISSUE TITLE
Add pending build status for build requests

### ISSUE THREAD

**Issue by chrwen-omicron** [buildbot/buildbot#4016]
This issue is meant to start a discussion.

We're using Buildbot in combination with GitLab where the status of builds get pushed to. Our problem is that GitLab doesn't know what builds might get started by a commit.
For example there might be no worker available or dependent builders. Because of that you can't tell in GitLab if a commit or merge request is fine. Additionally you can't use the automatic merge feature in merge request when the pipeline is green, because there might still be a build which hasn't started.
So I was thinking about something like adding/reporting a pending build status for build requests. That way they would be immediately available in GitLab.
I know there are a few things which have to be thought through, but I would like to hear some other opinions/experiences.

**Comment by staticfloat** [comment]
I'd like to second the request that status reporters be able to respond to a buildrequest.  In the Julia language project, we have a large number of builders, and it's not always easy to realize that a test hasn't even started yet because there were many other builds in the queue for one particular architecture (we have e.g. x86_64, i686, aarch64, across Mac, Windows, Linux, FreeBSD, etc...).  It would be helpful to be able to see a "pending" for all of these immediately so that a maintainer can quickly see the status of the build.
