### ISSUE TITLE
workers should be able to automatically delete leftover directory

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#4095]
Buildbot worker prints a warning about leftover directory:

> [Broker,client] I have a leftover directory 'xyz-tests' that is not being used by the buildmaster: you can delete it now

Reference: https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/base.py#L299

In large setups where configuration is dynamic and workers connect to different builders and builders change over time, it becomes a huge manual tasks to keep track of left-over directories and manually delete them. 

Buildbot worker should have an option to delete such left-over directories, (probably configurable somewhere, e.g. buildbot.tac or master.cfg)

**Comment by gpshead** [comment]
The lack of this behavior took two of my buildbots offline after the master made a configuration change that altered the directory suffixes used.

Instead of logging `I have a leftover directory 'BLAH' that is not being used by the buildmaster: you can delete it now` to a log file no human is going to monitor, just call `shutil.rmtree()` on it.

https://github.com/buildbot/buildbot/blob/cc304b5a4e656200853a41ba8abc6e3b3a58cb57/worker/buildbot_worker/base.py#L298

is where it'd be done.

(as seen due to https://github.com/python/buildmaster-config/pull/108 and https://bugs.python.org/issue38269)

**Comment by mojca** [comment]
#4750

**Comment by mojca** [comment]
Sorry for the too short response last time. I would be in favour of automatically cleaning things up, one just needs to be careful enough to not delete stuff that's still being used (two builders may use the same dir, for example; even though I might want a clean-up anyway), and that users might actually want to delete stuff which should have been removed before this functionality will be implemented.

**Comment by aj062** [comment]
Seems like this is fixed by https://github.com/buildbot/buildbot/pull/5160/files

**Comment by p12tic** [comment]
Indeed.
