### ISSUE TITLE
display the list of waiting builds for workers in homepage

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#4239]
In a given situation, there is no way to find the list of builds waiting for a worker. It will be helpful if we can have this list shown on home page.

**Comment by tardyp** [comment]
The list of builds waiting for a worker is named list of unclaimed buildrequests. It is available using the rest API at e.g:

https://nine.buildbot.net/api/v2/buildrequests?claimed=False

feel free to send a PR in order to add this info to the home page.

**Comment by aj062** [comment]
Home page or the specific worker page (or maybe a separate page)?

I have couple of thousand pending buildrequests at any given moment, having that complete list on buildbot homepage would make the homepage unusable for me.

**Comment by vvscloud** [comment]
A separate page will be a good idea.

**Comment by doberkofler** [comment]
I would love to have it in the Waterfall Views as it was in pre v1 releases.

**Comment by tardyp** [comment]
> I would love to also see it in the Waterfall Views as it was in pre v1 releases.

Yeah, this is another story.

Here is an answer to similar request I wrote on the mailing list a while ago:

>I agree on waterfall that it also needs some work.
Eight's waterfall is a very clever design from Warner, our first maintainer. It is tightly coupled with the status API, which has been designed for waterfall. 
There is a complex python generator based design which allow to build the waterfall progressively, from top to bottom.
Eight's waterfall and status are tightly coupled, this is the reason why we can't really reuse eight's waterfal code, even if we'd wrote a server side plugin.

>Nine REST API is on the contrary more generic, model and update oriented. It is KISS, decoupled, scalable, and much easier to test and maintain.
Eight's waterfall display the whole db in one view. changes, builds, steps, logs. So in order to implement it, you need to download the whole data.

>I doubt we can really do it with the current REST api, it would be too slow. This is why it currently only displays builds, but it's not that much useful.
I guess we would need a new dashboard centric REST api endpoint which allows to download all the data needed in one request.
