### ISSUE TITLE
Interpolate cannot be used in BuildStep name

### ISSUE THREAD

**Issue by lancelodliu** [buildbot/buildbot#4250]
I am using version 1.1.0 and Python 2.7.13.
In Windows, using `Interpolate` in a BuildStep's name is ok while in Linux, it complains about it:
```
2018-08-07 16:43:04+0800 [-] Configuration Errors:
2018-08-07 16:43:04+0800 [-]   BuildStep name must be a string: Interpolate('BuildCollisionAndHpa_Step: %(prop:SceneName)s')
```

**Comment by tardyp** [comment]
This is weird, as the code shows that renderable buildstep name are implemented:
https://github.com/buildbot/buildbot/blob/2676bd862ff59051fb0c3e7d73a38100016c1d1c/master/buildbot/process/buildstep.py#L344

since 0.9.10: https://github.com/buildbot/buildbot/commit/6ff917a44390070dcc22d75faca75d83b96a7c12

**Comment by tardyp** [comment]
Your error message suggests that you are not using 1.1.0, but rather something < 0.9.9

**Comment by lancelodliu** [comment]
Yes, my fault. I misused an older version of buildbot.
