### ISSUE TITLE
the NestedParameter can't support columns=5

### ISSUE THREAD

**Issue by smiledaylife** [buildbot/buildbot#4308]
i have modified the file forcesched.py in master/buildbot/schedulers:

# if self.columns > 4:
            # config.error(
                # "UI only support up to 4 columns in nested parameters")

But it doesn't work, so  I want to ask if there are anything else should be modified ?

**Comment by tardyp** [comment]
Hi, the columns is implemented here: https://github.com/buildbot/buildbot/blob/master/www/base/src/app/common/directives/forcefields/forcefields.directive.coffee#L46

This implementation works because 12/1 12/2 12/3 12/4 are all integers. would also work for 6 but not for 5

We need another implementation to support 5 columns, but the column will not be all the same size , because of the underlying bootstrap framework

https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by smiledaylife** [comment]
thanks! But it seems the parameters in NestedParameter field will get the same width through a loop?

If i want to make some implementations to support 5 columns, what can i do to give parameters  different number of 'col-sm' to make them have sum of 12

**Comment by tardyp** [comment]
This is a limitation of bootstrap grid layout system. you can use the floor(12/5)=>col-sm-2
but you will not use the full width.

Another option is to define our own grid system .. :-/

**Comment by smiledaylife** [comment]
Thank you for your advice. I think this is already the best solution to use floor.
