### ISSUE TITLE
Problems getting updated properties events from event stream

### ISSUE THREAD

**Issue by rpurdie** [buildbot/buildbot#4321]
I'm working on the "Yocto Console View", a version of the Console View customised to the needs of the Yocto Project. https://typhoon.yocto.io/#/console is a live instance of it, http://git.yoctoproject.org/cgit.cgi/yocto-autobuilder2/tree/yocto_console_view/src/module/main.module.coffee is the code.

During the build we set a couple of properties in a couple of steps, basically a steps.SetPropertyFromCommand(command=X), property="yp_build_revision"). My problem is getting the console view to see notifications of these property changes.

I've done a lot of digging and noticed something odd. The buildbot controller sends events that look like this (using the debug from mq/simple.py):
 MSG: ('builds', '123', 'properties', 'update')
        {'yp_build_revision': ('ae130de4ba287730d5f843019ecf8b8383b3741e',
                               'SetPropertyFromCommand Step')}

So the API sees a change to "builds/123/properties/update".

If I look at the code in buildbot-data/dist/buildbot-data.js, CollectionInstance() is called with restPath "builds/123/properties" but dataUtilsService.socketPath() turns this into "builds/123/properties/\*/\*". That in turn becomes a regex which does not match "builds/123/properties/update" since its short of an element.

I hacked the code to change */* to * for build properties and the code starts doing something much more like what I'd expect in that I start to see events when properties change, if I've specifically requested them. The build entries from getBuilds() don't seem to trigger onChange/onUpdate events when their properties change though. My code can then do:

        @builds.onNew = (build) =>
            build.getProperties().onChange = (properties) =>
                buildid = properties.endpoint.split('/')[1]
                if ! @maping[buildid]
                    rev = @getBuildProperty(properties[0], 'yp_build_revision')
                    if rev?
                        @maping[buildid] = rev
                        if not @onchange_debounce?
                            @onchange_debounce = @$timeout(@_onChange, 100)

which performs a lot better than what is in the repository (since it only looks at new builds), albeit still being horrible.

At this point I really need some advice as I'm out of my depth and am unsure what the bug is (if there is one). Its possible I'm just misunderstanding something. With that in mind some questions:

Is the correct event being sent out (builds/123/properties/update)?
Is the correct socketPath being used ("builds/123/properties/\*/\*")?
Should a getBuilds() onChange handler see notifications when properties of a build change?

**Comment by tardyp** [comment]
Good catch!
Properties are a bit specific, and does not exactly match the same pattern as the other REST endpoints.
I guess this is why the event watcher endpoint is wrong. It is generated automatically, and is wrong for that endpoint.

> Is the correct event being sent out (builds/123/properties/update)?

It is generated there, and as per comment is a bit specific: https://github.com/tardyp/buildbot/blob/1d9df393b1af6171716629cbc55fcb47f217e99a/master/buildbot/data/properties.py#L64
I think the reason for that is that we don't want to send an event for every single property change, it would cost too much on the event bus.

> Is the correct socketPath being used ("builds/123/properties/*/*")?

Probably not. This is implemented here generically: https://github.com/tardyp/buildbot/blob/1d9df393b1af6171716629cbc55fcb47f217e99a/www/data_module/src/services/data/collection/collection.service.coffee#L11
I don't see any solution other than doing some sort of "if properties" there in order to fix the event management for the particular case of properties.
For each endpoint, there is a class where you are supposed to implement particularities (https://github.com/tardyp/buildbot/blob/1d9df393b1af6171716629cbc55fcb47f217e99a/www/data_module/src/classes/properties.service.coffee#L7) but I really don't see how to implement that particular one, as is is only valid for the collection, and not the units.

> Should a getBuilds() onChange handler see notifications when properties of a build change?

Definitly not, as properties is a sub endpoint of builds. you don't get build updates when one of its step changed.

**Comment by rpurdie** [comment]
> I don't see any solution other than doing some sort of "if properties" there in order to fix the event management for the particular case of properties.
> For each endpoint, there is a class where you are supposed to implement particularities (https://github.com/tardyp/buildbot/blob/1d9df393b1af6171716629cbc55fcb47f217e99a/www/data_module/src/classes/properties.service.coffee#L7) but I really don't see how to implement that particular one, as is is only valid for the collection, and not the units.

Thanks for the answers, it matches what I thought might be the problem, I hadn't actually managed to track down the real source code to that function but now I know where it is! I've opened a pull request which fixes the socketPath function to generate the correct entry for properties.
 
> > Should a getBuilds() onChange handler see notifications when properties of a build change?
> 
> Definitly not, as properties is a sub endpoint of builds. you don't get build updates when one of its step changed.

I thought that may be the case but wanted to check, thanks!
