### ISSUE TITLE
Feature request: language agnostic protocol for master/worker communication

### ISSUE THREAD

**Issue by mlyszczek** [buildbot/buildbot#4344]
Hi,

Right now communication between master and slave is tightly integrated with python making it very hard to implement own slaves. Why implement own slave you ask? There are some platforms where deploying python with twisted is very hard (like minix) or python support is virtually non existant (like on nuttx). For those platform it would be usefull to have different slave, written for example in C or C++ language. But for that, API different than Perspective Broker is required (like mqtt which is lightweight and supports encryption).

And while I am willing to write slave in C, I am not strong enough with python to implement it properly on buildbot side, thus feature request.

**Comment by tardyp** [comment]
This discussion already happen on the ml. Copying and cleaning up my answer:

Options:

# wamp + cross bar

Here is my wamp proof of concept, which is very old and clunky.
https://github.com/buildbot/buildbot/pull/1526

It cannot really work now because it needs wamp routing capability of autobahn, which was available at that time, but not available anymore.
I did try to make it work over crossbar, but it does not make much sense, it was to unreliable to detect wether a worker was connected or not.

That poc does at least show what you have to implement to describe a new protocol backend.

# new protocol

The null protocol (made after that poc) is also a very good start to understand what api the upper layer are expecting to see.
https://github.com/buildbot/buildbot/blob/master/master/buildbot/worker/protocols/null.py

There are interop integration tests which are designed to be used for testing protocol implementation, and worker/master compatibility:
https://github.com/buildbot/buildbot/tree/master/master/buildbot/test/integration/interop

# XX over websocket

HTTP+websocket sounds like a well supported protocol on many platforms.
Then there is the problem of the serialisation. 
Protocol messages are not completely jsonable yet, but there is not much to do, as the wamp poc shows.

## json over websocket

json itself, is imho not very well suitable for protocol as most of the trafic is due to logs, which are byte streams, and json adds unnecesary back and forth encoding for those.

## amp over websocket

Twisted amp could be a good candidate to implement a new protocol. I think it would be a good idea to make it available over websocket, rather than using another port, this would allow to delegate authentication parts to the http stack, and the encryption part to an https frontend.
amp has implementation for c: https://amp-protocol.net/Implementations/
Problem with amp is that it is not very much used.

## protobuf over websocket (or GRPC)

Another good option for serialization and RPC would be protobuf, which is a bit more complex, but benefits from strong experience/support from Google. https://developers.google.com/protocol-buffers/

both amp and protobuf require separate specification of message, which is clearly a must have for a new protocol.

## messagepack over websocket

I think this could be the fastest and easiest option to start with. MessagePack is very fast on python, and the output is very dense.

# C or go

on the mailing list,  Dustin suggested to rather use go for implementation. I think go has good options for cross compilation and static binaries.
Go has very good support for http/https client and protobuf code generation.
If you really want c, for sure that will work too, but probably a little bit more work to make it secure/reliable.

Go might not however have the ubiquitness of C obviously (n

**Comment by p12tic** [comment]
I'm also interested in this as additional fiddling is needed on old systems due to old python and pip. 

Would C++ / gRPC work? Using modern C++ subset would almost eliminate chance of security and reliability problems associated with C and it's possible to make the resulting executables backwards compatible as far as we want by linking C++ standard library statically and binding to old versions of libc symbols via linker maps.

**Comment by tardyp** [comment]
I wasn't not a big fan of gRPC as the protocol-buffer compiler was java afair.
Now it looks like they rewrote it in cython, which looks cool to me. 
C++ is cool to me as well, and it has now support in lots of embedded stuff. probably we need to be very careful at keeping the code as simple as possible.
Looking at the grpc doc it has async for client, which imho is very important for buildbot workloads.

The problem I can see is that buildbot protocol needs RPC both in client and server. 
We want server to be the master and client to be the worker. This helps a lot to protect the worker as the worker are the connection initiator. This means you can put your worker behind NAT firewall.

With PB, once you initiate a connection, then you can do RPC in both direction. We use this feature in the buildbot protocol. 
When master starts a build, it sends an RPC to the worker.
When worker gets some stdio, it sends a status RPC to the master.
All goes through the same worker initiated tcp connection.
GRPC being HTTP2 based, I think it will be not straighforward to implement this. you would need to make some sort of long polling call from worker like getNextBuild(). I think this is fine, but we need to be aware of that.

A pure websocket+msgpack protocol would make it more straighforward, but may require a bit more lowlevel boilerplate. The benefit of that is that you are very flexible to make the minimal level of complexity that suits your problems.

**Comment by p12tic** [comment]
Thanks for your thoughts. 

Indeed, GRPC does not look like a perfect fit for this purpose even if the ability to specify protocol separately and just have the code generated is so compelling :-). I think GRPC does support connection keepalive, so I think we could have server-initiated build start. But on the other hand, HTTP2 is yet another protocol that any HTTP reverse proxies between internet and the master would need to support. They must already support websockets for the web frontend so sticking with websockets would be a simplier option in this regard too.

Since the protocol is relatively simple, websockets and msgpack is probably better solution.

**Comment by yan12125** [comment]
(replying https://github.com/buildbot/buildbot/issues/4344#issuecomment-426247674)

> on the mailing list, Dustin suggested to rather use go for implementation. I think go has good options for cross compilation and static binaries.

I'm not sure if Go is still a good choice or not, but [Gitlab Runner](https://docs.gitlab.com/runner/) from GitLab CI uses Go with similar advertising statements:

> GitLab Runner is written in Go and can be run as a single binary, no language specific requirements are needed.

(excerpted from https://docs.gitlab.com/runner/#requirements)

Their runner might come with less features than buildbot, though.

Sorry if Go is already rejected. I didn't find discussions about this feature request on the mailing list devel@buildbot.net.

**Comment by p12tic** [comment]
We want the buildbot runner to work on any platform for the foreseeable future. Go and similar languages only work on platforms that their runtime supports.

See Go release notes for an example of problems that could be caused by this choice:

> Go 1.11 now requires OpenBSD 6.2 or later, macOS 10.10 Yosemite or later, or Windows 7 or later; support for previous versions of these operating systems has been removed.

Some people may want to test ancient or weird platforms. For the happy path we already have the Python runner. For unhappy path we should not limit ourselves in my opinion :-) Requiring only a working C++ compiler is the smallest requirement we can choose without having to spend too much time developing the implementation :-)

A second reason is that I know C++ really well and plan to contribute to buildbot for the foreseeable future. Thus there are some guarantees that regardless of who develops the worker it will be maintained.

**Comment by yan12125** [comment]
I see the rationale for not using Go. Thank you very much for clarification!

By the way, as the packager of the official Arch Linux buildbot package [1], I'm glad to see buildbot is not going to embrace Go. Go brings much headache when we are trying to make Arch Linux packages reproducible.

[1] https://www.archlinux.org/packages/community/any/buildbot/

**Comment by dankegel** [comment]
Where's the latest discussion on this?

**Comment by tardyp** [comment]
I've been thinking about this a bit more lately. 
Problem with c++ is that it is not that portable on a system API level. With python, you get batteries included for all the system it supports.

With C++, you have STL, which has no portable process management, or network library. 
Also we should probably avoid targeting c++17 if we look for portability, even if it might have lot of nice features for us.

So that could be one of:

-  C++ and https://libevent.org/
-  C++ and https://libuv.org/
-  C++ and https://github.com/cesanta/mongoose (mongoose is quite popular in embedded and very portable even for real time os)
- C++ and GRPC (grpc async api uses its own event loop, and do not look to have strong interop support https://github.com/grpc/grpc/issues/7352)

On all of those, only libuv has portable subprocess management (i.e creating subprocess for our ShellCommand, follow their output and reaping them when they die)
On python/twisted, this has proven to be one of the major burden in my experience, especially on Windows.

**Comment by p12tic** [comment]
Agreed with everything above. I think that feature-wise, using C++11 as the lowest common denominator just for the language features makes sense, C++98 is too inconvenient.

The problem on old systems is not even STL, because we can link it statically. The problem is the C library, because it's too intertwined with the system we'll be running at, so must be linked dynamically. I researched this a little bit and it looks like that one can limit ourselves by the API exposed by an old libc (don't remember exactly how though). This is all problem on Linux only, because newer compilers usually only target newer libc.

As for the networking library, we should also look into [boost.asio](https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/overview/implementation.html). Having worked with boost extensively, It is my understanding that it attempts to support almost everything under the sun, even the weirdest platform/compiler combinations.

**Comment by mlyszczek** [comment]
I don't think it's the right time to think about another slave implementation now. Implementing language agnostic protocol does not really care about in what language client will be implemented. This will make buildbot more open for different languages, since implementing Perspective Broker in c/c++/rust/go/etc is cumbersome at best.

I say, now is the time to choose protocol that will be easiest to implement on different platforms/languages and implementation should have different feature request/task.

My vote would go to mqtt+json. mqtt is small, has client implementation for many languages, topics are really cool way to filter/subscribe events (for external monitoring software), supports encryption on protocol level. And json is nice human-readable data format.

mqtt+json can be easily used in powerful amd64 machines as well as on very small arm cortex-m microcontrollers. And yes, this feature request was made just so I could have buildbot client on MCUs to test embedded software:-) And it is vital that this new protocol be as small and as portable as possible, since it will be most probably used on those weird and resource constraint machines where python is not available (because why would you not used official worker if you have python and enough of resources to run it?:-))

So please, let's not talk about languages and implementation but rather protocol/data format.

**Comment by tardyp** [comment]
I think both language vs protocol should be discussed together as a whole proble. We are not going to maintain more than 2 worker implementation, so langage portability of a protocol is not that much of a problem.

GRPC also is a protocol that is very portable, but.. when you look at the detail, the implementation of c++ seems to not work well with process management.

Really for me the hardest problem is to manage the process, this is mostly the only thing you ask to a worker, so we should make sure our choice do not make that harder.

As per mqtt + json, this protocol is made for small embedded CPUs indeed, but tailored to small infrequent messages (the use case of the IOT). I see those disadvantages:

- mqtt + json is text protocol. 
      Yes it is simple, but this will be quite inefficient for transferring large logs, or artifacts.
      We need to have something which scales on both sides.
      text protocol needs to deal with char encoding, and escaping, so this can be very inefficient.
- mqtt do not pass http proxy, which is a huge burden in large enterprise.
- I have not found very convincing implementation of mqtt in async for python or c++. There is twisted-mqtt but it looks very PoC level code, paho is industry standard, but it is all based on ac implementation with its own async framework (like grpc)

Some users run performance measurement tests with Buildbot, and needs to have the lowest overhead as possible from the protocol, that's another reason why I was suggesting a binary protocol.
Even if websocket/https is order of magnitude more complex, it is also so much ubiquitous, with several very mature implementations in all languages and platforms..

**Comment by p12tic** [comment]
One additional thing to think about is that if we picked a library that allows one to use only what you need, then we could easily have two or more tiers of BuildBot worker with varying amount of functionality enabled. For microcontrollers binary size is at premium so having a bare bones worker that only supports HTTP and websockets makes sense and we could have that just by using some `#ifdef`s.

**Comment by tardyp** [comment]
Boost.asio indeed looks like very very portable. There is native support there for both websocket or mqtt
https://github.com/redboltz/mqtt_cpp
https://github.com/boostorg/beast

As long as the messages are json-like, I think we could swap the lower level quite easily at least in the python master side

**Comment by mokibit** [comment]
Hi,
I am currently working on this feature. Master and worker will communicate through MessagePack over WebSocket protocol.  All master-worker commands work using this new protocol, except "uploadFile", "uploadDirectory", "downloadFile". Specification is also nearly done.

**Comment by tardyp** [comment]
wow! super cool!

**Comment by p12tic** [comment]
The MessagePack-based master-worker protocol has been in Buildbot for quite some time. Closing the github issue.
