### ISSUE TITLE
ldap authentication "501 not implemented"

### ISSUE THREAD

**Issue by angeloudy** [buildbot/buildbot#4360]
Can anyone provide an example of LDAP authentication.
I followed the manual and couldn't make it work.
According to the manual
```
from buildbot.plugins import util

# this configuration works for MS Active Directory ldap implementation
# we use it for user info, and avatars
userInfoProvider = util.LdapUserInfo(
    uri='ldap://ldap.mycompany.com:3268',
    bindUser='ldap_user',
    bindPw='p4$$wd',
    accountBase='dc=corp,dc=mycompany,dc=com',
    groupBase='dc=corp,dc=mycompany,dc=com',
    accountPattern='(&(objectClass=person)(sAMAccountName=%(username)s))',
    accountFullName='displayName',
    accountEmail='mail',
    groupMemberPattern='(&(objectClass=group)(member=%(dn)s))',
    groupName='cn',
    avatarPattern='(&(objectClass=person)(mail=%(email)s))',
    avatarData='thumbnailPhoto',
)
c['www'] = dict(port=PORT, allowed_origins=["*"],
                url=c['buildbotURL'],
                auth=util.RemoteUserAuth(userInfoProvider=userInfoProvider),
                avatar_methods=[userInfoProvider,
                                util.AvatarGravatar()])


```

And I am getting
```
web.Server Traceback (most recent call last):
twisted.web.error.Error: 501 not implemented 
```

**Comment by tardyp** [comment]
hello. Please give the full traceback so that we can help

**Comment by angeloudy** [comment]
@tardyp 
full traceback as following:
```
2018-10-19 15:59:52+1100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 2099, in lineReceived
	    self.allContentReceived()
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 2190, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 917, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 194, in process
	    resrc = self.site.getResourceFor(self)
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 853, in getResourceFor
	    return resource.getChildForRequest(self.resource, request)
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/resource.py", line 98, in getChildForRequest
	    resource = resource.getChildWithDefault(pathElement, request)
	  File "/usr/local/lib/python3.6/site-packages/twisted/web/resource.py", line 201, in getChildWithDefault
	    return self.getChild(path, request)
	  File "/usr/local/lib/python3.6/site-packages/buildbot/www/auth.py", line 49, in getChild
	    return self.master.www.auth.getLoginResource()
	  File "/usr/local/lib/python3.6/site-packages/buildbot/www/auth.py", line 67, in getLoginResource
	    raise Error(501, b"not implemented")
	twisted.web.error.Error: 501 not implemented



```

**Comment by tardyp** [comment]
Hi @angeloudy , with

                auth=util.RemoteUserAuth(userInfoProvider=userInfoProvider),

The ldap authentication is meant to be done by a reverse proxy like apache
https://httpd.apache.org/docs/trunk/en/howto/auth.html

With this, you can do the auth with ldap or kerberos.

ex config with kerberos is here:
http://docs.buildbot.net/latest/manual/cfg-www.html#buildbot.www.auth.RemoteUserAuth

There is no example yet for ldap in buildbot doc.
You can find example with google, e.g:
https://gist.github.com/chrisglass/634089 (unverified by me)

**Comment by angeloudy** [comment]
@tardyp Thanks.
I've got the authentication working with apache reverse proxy. But the upper right corner, it does not display the username but 'anonymous'. I had the 'REMOTE_USER' header set in my apache config. 
I am not sure what I did wrong.

Is there a complete example of apache configuration I can follow?

**Comment by btgoodwin** [comment]
@angeloudy Were you able to resolve your REMOTE_USER problem?  I'm using nginx (FWIW).

**Comment by gvalkov** [comment]
Hi @btgoodwin - I ran into this issue while setting up buildbot behind nginx (with nginx handling the ldap authentication). Turns out that `RemoteUserAuth` expects `REMOTE_USER` to be in the  `$user@$realm` format. It's possible to change the regex with the `headerRegex` argument to `RemoteUserAuth`.

**Comment by btgoodwin** [comment]
Hi @gvalkov.  Thanks for the response; I've seen several indications that I needed to get NGINX and BuildBot's RemoteUserAuth header to sync (i.e., `REMOTE_USER` vs. `X-Remote-User`) but no one has mentioned the header regex as also a need.

For NGINX and LDAP I tried for a while to compile in the one LDAP solution and couldn't get it working.  I then switched over to the one listed on the NGINX website wiki (involves a docker container, daemon, etc.) but could not get past how to get the login page redirect to work with their posted example.

I ultimately switched to using the NGINX PAM module (since the server is already using it for access control) to authenticate the whole site.  However even when using RemoteUserAuth, it still doesn't seem to be getting the right header information (I assume), so I get the 501 error listed here.  Can you provide more information about your NGINX setup for this, for example, did you have to include underscores and set the `REMOTE_USER` header variable to a different format or did you manipulate your buildbot configuration to match what was being sent?  How did you view what was being sent to discover this problem?

**Comment by gvalkov** [comment]
I got it running with [nginx-ldap-auth-aiohttp](https://github.com/gvalkov/nginx-ldap-auth-aiohttp) and the following configuration:

```nginx
server {
    listen 80;
    root html;
    index index.html index.htm;
    server_name ...;

    proxy_set_header HOST $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-Server  $host;
    proxy_set_header X-Forwarded-Host  $host;

    location = /auth-proxy {
        internal;

        proxy_pass http://unix:/run/nginx-ldap-auth/server.sock:/;

        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        proxy_set_header X-Ldap-URL      "...";
        proxy_set_header X-Ldap-Realm    "...";
        proxy_set_header X-Ldap-BaseDN   "...";
        proxy_set_header X-Ldap-BindDN   "...";
    }

    location / {
        auth_request /auth-proxy;
        auth_request_set $auth_user $upstream_http_AUTHENTICATED_USER;
        auth_request_set $auth_dn $upstream_http_AUTHENTICATED_DN;
        proxy_set_header REMOTE_USER $auth_user;
        proxy_pass http://buildbot:8080/;
    }
    location /sse/ {
        # proxy buffering will prevent sse to work
        proxy_buffering off;
        proxy_pass http://buildbot:8080/sse/;
    }
    # required for websocket
    location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://buildbot:8080/ws;
        # raise the proxy timeout for the websocket
        proxy_read_timeout 6000s;
    }
}
```

```python
...
c["www"] = {
    "port": 8080,
    "auth": RemoteUserAuth(userInfoProvider=auth, headerRegex=r"(?P<username>.+)"),
    },
}
...
```

Hope it helps!

**Comment by btgoodwin** [comment]
Thank you so much! I can't believe I never ran across that project of yours.  If I don't get around to implementing this tonight, I'll report back once I get back in a week.

**Comment by btgoodwin** [comment]
My server doesn't support anonymous binding or autobind, it seems, so I patched those changes into your `server.py`:

```
def authenticate_user(request, config):
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.lower().startswith('basic '):
        raise SendChallenge()

    auth_data = auth_header.split(None, 1)[-1]
    auth_data = base64.b64decode(auth_data).decode('ascii')
    username, password = auth_data.split(':', 1)

    if '%s' in config['X-Ldap-BindDN']:
        binddn = config['X-Ldap-BindDN'] % username
        log.debug('Performing anonymous bind with "%s"', binddn)
        conn = connect_ldap(config['X-Ldap-URL'], binddn, password, auto_bind=False)
        if not conn.bind():
            log.error('Anonymous bind error for user "%s": %s', binddn, conn.result)
            raise SendChallenge()

        return username, binddn

    else:
        conn = connect_ldap(config['X-Ldap-URL'], config['X-Ldap-BindDN'], config['X-Ldap-BindPW'], auto_bind=False)
        conn.bind()
        exists = conn.search(config['X-Ldap-BaseDN'], '(objectClass=*)', ldap3.SUBTREE, attributes=['objectClass'])

        if not exists:
            raise SendChallenge()
        return username, 'cn=%s,%s' % (username, config['X-Ldap-BaseDN'])
```

Then at the NGINX configuration, I added the extra `X-Ldap-BindPW` header.

When I go to my site, it repeatedly asks me to sign in and never navigates away even when I know the credentials are correct.  I see no errors at your auth daemon, NGINX, or buildbot (even with invalid credentials).

Is there another redirect that needs to exist?

**Comment by btgoodwin** [comment]
Something else interesting -- I enabled anonymous binding on the server (Windows) and was able to use `ldapsearch` to query the OU.  Several users don't have any additional information beyond their DN (e.g., sAMAccountName) even though those attributes exist at the server.  And for the DN, all are setup like: `CN=Real Name,OU=group,DC=...` rather than the username, and replacing `cn` with `sAMAccountName` (which is set to the username for those that have it) is not a valid DN.  So this might all just be unworkable for Active Directory.

**Comment by btgoodwin** [comment]
@gvalkov I figured out a solution by implementing the bind user section of your server.  I've submitted a PR for it.  Thanks again for your help!

**Comment by p12tic** [comment]
Ultimately the issue that caused the bug was bad handling of warnings. The current code (and code 4 years ago) spews errors outlining the reason for the failure to authenticate. There are error messages for both missing header and header not matching the regex. The intention of the code is to bring these to the web UI, but this doesn't work right now.

I've opened a separate issue https://github.com/buildbot/buildbot/issues/6924 for the failure to display warnings and will close this bug.
