### ISSUE TITLE
Latent Docker: Add volumes to builders

### ISSUE THREAD

**Issue by bog-dan-ro** [buildbot/buildbot#4808]
Cloning large projects requires a lot of time, so we need a way to cache the srcs between builds.
 While it's possible to add volumes to a DockerLatentWorker it's not enough to cache and **isolate** the builds because all the projects will see all the other projects sources. (e.g. ` -v /cache/projecs:/home/buildbot/project`).

An ugly workaround will be to add a worker for each builder but ... it's uber ugly.
Will be nice if we can pass to builderConfig additional volumes as in that moment we can map a cache path specific to that project/builder (e.g. `-v /cache/projects/Interpolate("%(prop:name)s"):/home/buildbot/project`). This way this project will see only its own cache.

**Comment by p12tic** [comment]
@bog-dan-ro Turns out Buildbot supports this feature and has supported for years, at least since 0.9.x.

The volumes argument is renderable which means you can pass the following to it:

`Interpolate(/cache/projects/%(prop:name)s:/home/buildbot/project)` 

and it will work like you would expect.

In more complex cases you can pass a renderer function and run arbitrary code that depends on exact build properties at the moment just before container startup.
