### ISSUE TITLE
builders page is slow, need search-ish alternative or a filter

### ISSUE THREAD

**Issue by dankegel** [buildbot/buildbot#4869]
The builders page takes about five seconds to load, and even after it loads, finding the builder in question amongst the thousands of builders is hard.  Users have taken to doing things like
```
#!/bin/sh
# wmb - Dude, where's my builder?
curl -sS http://buildhost5.example.com:8010/api/v2/builders | jq '
[.builders[]
 | select(.name | match($search))
 | {name:.name, link: @uri "http://buildhost5.oblong.com:8010/#/builders/\(.builderid)"}]
 | sort_by(.name)
' --arg search "$1"
```

That lets users quickly find the URLs for the builders of interest... but it'd be nice if the
front page had a search box that did the same thing, so they didn't have to resort to
the commandline.

**Comment by p12tic** [comment]
How many builders do you have? Are you using HTTP2?

**Comment by dankegel** [comment]
About 4000 builders.

I'm not using a proxy, just straight up buildbot and chrome, with no special networking tweaks.

**Comment by mojca** [comment]
This is one of the pages that needs filtering by tags, other than console view (#3470) and waterfall (#3471).

In case virtual builders will be implemented in the scope of @rajdeepbharati's GSOC projects, this will definitely be needed for us as well.

Search field could make sense. @rajdeepbharati implemented a special view for MacPorts, but again, if we end up using 20k+ virtual builders, search field on builders page (and probably some property to allow hiding some virtual builders by default) could be used instead of a special view).

I'm not talking about addressing the performance yet, but at least to start with the way of filtering tags, and then continue from there later.
