### ISSUE TITLE
enterprise github hooks not working with buildbot

### ISSUE THREAD

**Issue by vvscloud** [buildbot/buildbot#5151]
We have our private github server , and configured hooks for push request.  upon making a test push, we did not observe any build getting triggered or any log in twistd. 
Is git hooks supported for private github repositories? any way to verify the hooks / see the logs for errors? upon checking the payload URL we are getting this message:
Unknown content type: None

Please help.

**Comment by tardyp** [comment]
Hello.
It is supposed to work, but we do not have continuous integration for it.
The logs are in twisted.log
Can you please provide the full error, and on which condition do you have this error?
Also github provides a debug interface, and shows the answer of the webhook if any.
This usually helps understanding the issue.

a good way of debuging is the good old tcpdump/wireshark and see what happens (with https disabled)
You can also share those dumps here, so that we can help.
Regards
Pierre

**Comment by vvscloud** [comment]
Hi @tardyp , Thank you, I am able to debug and it is working now. I am able to receive the  push events from hook and trigger the build. 
Can you please help to explain more on "_we do not have continous integration for it_" means? want to understand more as I am a novice user here.
