### ISSUE TITLE
Customisation for prioritizeBuilders doesn't work

### ISSUE THREAD

**Issue by jocelynj** [buildbot/buildbot#5193]
```shell
$ buildbot --version
Buildbot version: 2.0.1-2
Twisted version: 18.9.0
```

I'm trying to use the function prioritizeBuilders() documented on http://docs.buildbot.net/latest/manual/customization.html#builder-priority-functions
```python
def prioritizeBuilders(buildmaster, builders):
    """Prioritize builders. First, prioritize inactive builders.
    Second, consider the last time a job was completed (no job is infinite past).
    Third, consider the time the oldest request has been queued.
    This provides a simple round-robin scheme that works with collapsed builds."""

    def isBuilding(b):
        return bool(b.building) or bool(b.old_building)

    builders.sort(key = lambda b: (isBuilding(b), b.getNewestCompleteTime(), b.getOldestRequestTime()))
    return builders

c['prioritizeBuilders'] = prioritizeBuilders
```

But I'm getting the following error on twistd.log:
```
2020-02-10 21:46:30+0000 [Broker,0,127.0.0.1] prioritizing builders; order unspecified
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/lib/python3/dist-packages/buildbot/process/buildrequestdistributor.py", line 435, in _sortBuilders
	    builders = yield defer.maybeDeferred(sorter, self.master, builders)
	--- <exception caught here> ---
	  File "/usr/lib/python3/dist-packages/buildbot/process/buildrequestdistributor.py", line 435, in _sortBuilders
	    builders = yield defer.maybeDeferred(sorter, self.master, builders)
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
	    result = f(*args, **kw)
	  File "/data/work/buildbot-master/master.cfg", line 92, in prioritizeBuilders
	    builders.sort(key = lambda b: (isBuilding(b), b.getNewestCompleteTime(), b.getOldestRequestTime()))
	builtins.TypeError: '<' not supported between instances of 'Deferred' and 'Deferred'
```

How can I modify the function to make it working?

**Comment by tonyhutter** [comment]
I'm getting the exact same error with 2.7.0 using the same example code.  I'm not 100% sure, but I believe it's because `getNewestCompleteTime()` and `getOldestRequestTime()` have `Deferred` return values.  `Deferred` functions return asynchronously.  So it's saying you can't compare the results of two asynchronous functions, which makes sense. 

Here's the commit that added it in: https://github.com/buildbot/buildbot/commit/629abaa44ec2b5890ac8683c434ad4d3593f4110

@jsonn can you comment on this?

**Comment by jsonn** [comment]
I haven't had time to update my buildbot instance in a while, so it is quite possible that it got broken by API changes in the last 2.5 years.

**Comment by ynezz** [comment]
This part of documentation is probably out of sync for some time and not working as expected. There are probably some issues with `BuildRequestDistributor` as described in #4592

> This provides a simple round-robin scheme that works with collapsed builds

I think, that this is misleading, because:

 * `getNewestCompleteTime()` relies on `complete_at` which gets updated with current timestamp when the new collapsed buildset is created and all current unclaimed build requests get marked as completed with SKIPPED result
 * `getOldestRequestTime()` relies on `submitted_at` which means almost same timestamp for all build requests when using collapsed builds

So instead of desired round-robin scheme one gets alphabetically or randomly sorted builders in most cases.

**Comment by krzk** [comment]
I had the same issue. I fixed it up with code borrowed from buildrequestdistributor.py: https://github.com/krzk/tools/commit/463adf3494ff775c347f70aade1a23b688fc2878

**Comment by terencehonles** [comment]
It looks like the documentation probably was fixed since this was reported and the example probably now works. The current documentation shows:

```python
@defer.inlineCallbacks
def key(b):
    newest_complete_time = yield b.getNewestCompleteTime()
    oldest_request_time = yield b.getOldestRequestTime()
    return (isBuilding(b), newest_complete_time, oldest_request_time)
```

which will resolve the deferreds before comparing them which was the issue with the sort above which is comparing the successive tuple values against each other and deferreds cannot be compared with `<`

That being said, I'm not completely sure the documentation is correct because I think I'd expect a `yield async_sort(builders, key)` in order to run the deferreds inside `async_sort`.

**Comment by jocelynj** [comment]
@terencehonles: you might be right. The code from the documentation crashes with this, at least on version 3.8.0:
```
2024-06-16 14:27:40+0000 [-] prioritizing builders; order unspecified
        Traceback (most recent call last):
          File "/var/lib/buildbot/.venv/lib/python3.11/site-packages/buildbot/process/buildrequestdistributor.py", line 353, in resetPendingBuildersList
            yield self._sortBuilders(
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1905, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1815, in _cancellableInlineCallbacks
            _inlineCallbacks(None, gen, status)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
            result = current_context.run(gen.send, result)
        --- <exception caught here> ---
          File "/var/lib/buildbot/.venv/lib/python3.11/site-packages/buildbot/process/buildrequestdistributor.py", line 408, in _sortBuilders
            builders = yield sorter(self.master, builders)
          File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1901, in unwindGenerator
            raise TypeError(
        builtins.TypeError: inlineCallbacks requires <function prioritizeBuilders at 0x7ffa343751c0> to produce a generator; instead got [<Builder ''x1'' at 140712733727952>, <Builder ''x2'' at 140712733728336>, ...
```

Adding your proposed `yield` fixes the crash, but I need to check if buildbot sends jobs in the expected order.

**Comment by jocelynj** [comment]
I had to rewrite the function `b.getNewestCompleteTime()`, as it is considering as completed previous buildrequests that were cancelled by a newer buildrequest by option `collapseRequests`, with this function:
```python
    @defer.inlineCallbacks
    def getNewestBuild(b):
        """Returns the complete_at of the latest completed build for
        this builder, or an old date if there are no such build requests.

        @returns: datetime instance or None, via Deferred
        """
        bldrid = yield b.getBuilderId()
        completed = yield b.master.data.get(
            ('builders', bldrid, 'builds'),
            [resultspec.Filter('complete', 'eq', [True])],
            order=['-complete_at'],
            limit=1,
        )
        if completed:
            return completed[0]['complete_at']
        else:
            return datetime.datetime.datetime(2000, 1, 1)
```
(`return None` is also changed, because `async_sort()` is not able to sort between `None` and `datetime`)

**Comment by jocelynj** [comment]
Closing ticket, now that the documentation was fixed.
