### ISSUE TITLE
Hipchat no longer available

### ISSUE THREAD

**Issue by rajdeepbharati** [buildbot/buildbot#5242]
https://status.hipchat.com/

https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/hipchat.py

Should hipchat reporter be kept any more?

**Comment by seankelly** [comment]
My vote is to remove it, but it's possible people are still running HipChat Server locally. If that's happening, I doubt any will notice this bug and chime in to keep it, so I vote removing it.

**Comment by p12tic** [comment]
> it's possible people are still running HipChat Server locally

Hmm, I think it makes sense to wait some months until all migrate. The reporter does not have maintenance cost, so removing it only has potential downsides.

**Comment by p12tic** [comment]
Turns out that there's a small maintenance cost, as all reporters are being migrated on top of `ReporterBase`. Thus `HipChatStatusPush` will be deprecated in Buildbot 2.10 and removed in 3.0.

I'm closing this issue as we've addressed the fact that the service is no longer available by deprecating `HipChatStatusPush`.
