### ISSUE TITLE
unauthorized login; check worker name and password

### ISSUE THREAD

**Issue by buck-E** [buildbot/buildbot#5383]
After removing pip from the system and installing `buildbot-worker` with apt on Debian now I can't restart this worker with `buildbot-worker restart` but get this error:

```
2020-06-24 06:23:42+0200 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x7f22783491f0>
2020-06-24 06:23:42+0200 [Broker,client] ReconnectingPBClientFactory.failedToGetPerspective
2020-06-24 06:23:42+0200 [Broker,client] unauthorized login; check worker name and password
```

I checked that the username and password are correct and the same in `master.cfg` and the buildmaster host is set correctly (127.0.0.1).  

I removed old processes of buildbot-worker

What debugging steps should I take?

**Comment by tardyp** [comment]
Hello,
This kind of issue is always an overlook somewhere. you may want to reboot the whole thing and make sure the config are actually what is loaded in memory.

**Comment by buck-E** [comment]
> you may want to reboot the whole thing

How exactly?  Rebooting the server is definitely not possible at this time.  Just restart buildbot-master?

> This kind of issue is always an overlook somewhere.

Right.  Where should I begin to debug?

**Comment by p12tic** [comment]
Several examples on which I myself wasted more time than I want to admit:

 - worker simply uses different password or name than the master expects
 - master is not using the most recent version of the configuration
 - there are actually two masters running on different ports, the second master is forgotten and uses old version of the configuration. Worker connects to that master and ends up using wrong password and/or name

All of the above can be fixed by shutting down all worker and master services, making sure there's no worker or master running and then restarting the services.

**Comment by buck-E** [comment]
I wish I knew why but this is working now.  All I did was get some sleep.  Closing.

**Comment by boweiliu** [comment]
I also ran into this, the issue was incorrect worker names in master.cfg

**Comment by mannp** [comment]
I am getting the same atm, all seems a little flaky.

**Comment by teto** [comment]
just had the same issue although I am pretty sure I had names and password lined up between master and worker. I got it fixed by setting the number of workers and cores to the same value (since I was seeing auth rejection for `worker-N00X` in the logs). That seems to have fixed it for me. Might be a red herring but wanted to share anyway
