### ISSUE TITLE
Missing tags for buildbot 0.8.13 and 0.8.14

### ISSUE THREAD

**Issue by aparcar** [buildbot/buildbot#5452]
Hi, I happen to know an instance of Buildbot that runs on 0.8.12, which seem to be tag-wise the latest 0.8.x release, however [on PyPi](https://pypi.org/project/buildbot/0.8.14/) are two more releases. Are there any further information on the difference?

**Comment by p12tic** [comment]
Thanks for noticing this.

It looks like 0.8.13 was a bad release with no files. I've yanked it out Pypi so that it does not confuse anyone else.

According to the files in the release, 9df5d7d2a4db811fde4780cc1555453ee0f12649 is the commit that corresponds to 0.8.14. I've tagged it and pushed to the BuildBot repository.
