### ISSUE TITLE
How to get HashiCorp Vault secrets?

### ISSUE THREAD

**Issue by vx-i** [buildbot/buildbot#5482]
I'm studying the buildbot documentation the whole day, but still don't understand how to get secrets from HashiCorp Vault instance. The error message that I get is:

...
2020-08-20 14:35:01+0200 [-] BuildStep.failed; traceback follows
	Traceback (most recent call last):
	--- <exception caught here> ---
	  File "c:\localdata\buildbot\.venv\lib\site-packages\buildbot\process\buildstep.py", line 555, in startStep
	    yield defer.gatherResults(dl)
	twisted.internet.defer.FirstError: FirstError[#14, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#3, [Failure instance: Traceback: <class 'KeyError'>: 'secret key 000/test is not found in any provider'
...

Builbot version 2.8.2
Vault path is /v1/kv/data/000/test

master.cfg
---
c['secretsProviders'] = [secrets.HashiCorpVaultSecretProvider(
                        vaultToken="mytoken",
                        vaultServer="https://myhostname:8200",
                        secretsmount="kv",
                        apiVersion=2
)]

factory = util.BuildFactory()
factory.addStep(steps.ShellCommand(command=["PowerShell.exe", "-Command",
                                          "& {Write-Host ", util.Secret("test")]))
...

If I do the query from Postman, I get "200 OK" answer and of course json data.

Do I missing some steps?

**Comment by p12tic** [comment]
Thanks for the bug report.

What you see is interesting... It seems like the provider is somehow not being registered to Buildbot. Could you edit master/buildbot/secrets/manager.py in your virtualenv and in the SecretManager.get function add logging of all available providers? 

```
from twisted.python import log
providers = [provider.__class__.name for provider in self.services]
log.msg('BB PROVIDERS', '[{}]'.format(', '.join(lines)))
```

**Comment by vx-i** [comment]
@tardyp I'm using Buildbot and Vault and you are right, it's probably easier for me to understand the requirements. At the moment I would like to see key name more flexible. I also think the error message should be improved. Access is given, path is OK, but only key name was wrong.

I'll take a look at the code and create a PR. Do you have more ideas around Vault?

**Comment by terencehonles** [comment]
> @tardyp I'm using Buildbot and Vault and you are right, it's probably easier for me to understand the requirements. At the moment I would like to see key name more flexible. I also think the error message should be improved. Access is given, path is OK, but only key name was wrong.
> 
> I'll take a look at the code and create a PR. Do you have more ideas around Vault?

I was playing with the secrets recently for my own setup, and I was just curious about this discussion. I looked and it doesn't look like you could easily use a tuple instead of a string for a secret value, but perhaps you could do the following:

https://github.com/buildbot/buildbot/commit/f2d0288d6f924919073420e20913310a6b59c389

I also am not sure if the KeyError that is already in the file is a bug or just doesn't work (and the KeyError I added wouldn't work either).

You're allowed to have multiple secret providers and I believe the expectation was that they should only return `None` or the valid secret. In the case that there is a partial secret match it's probably OK enough to flag that the secret prefix was found, but not the suffix.

The change I made uses "/" as a separator because it looks like that's the only invalid character according to [this message](https://groups.google.com/g/vault-tool/c/_E2N0SLryv8) other than that I didn't find anything suggesting other invalid characters. I was initially going to use ":". The change preserves existing functionality and the two secrets will be resolved to the same thing `Secret('test')` and `Secret('test/value')`, and to specify some other attribute `Secret('test/secret_attibute')`.

I'll let you all figure out if this makes sense and add the needed tests for this change.

**Comment by vx-i** [comment]
@terencehonles I really like your idea, but it doesn't work. Yet.

Vault is doing everything with paths and if you are using separator with "/" then you also split paths. For example:

Path: kv/000/test
Entry: 000/test/value
Key: value
Value: verysecret

The outcome with your code:

entry: 000/test/value
name: 000
key: test/value

So we only need to split the last "/". That would mean, we have vault/path/to/secret/key_name and the result will be

name: vault/path/to/secret
key: key_name

What do you think?

**Comment by terencehonles** [comment]
I should have left it as rpartition, I was thinking about that with ":" when I was thinking about what was valid for the path. In your example it looked like you had used "test" as the secret so I wasn't sure where the "000" was coming from and it seemed like the mount could take care of most of the path, and the secret name had no "/"s in it. If it does need to have "/"s in it I think rpartition would work well enough. You could also potentially change it to ":" if you think it's unlikely that a secret key would have a ":" in it.

Feel free to take the commit and suggest an appropriate PR!

**Comment by pavelgk** [comment]
We've discussed the issue with @vx-i . If you don't mind I'll take care of PR.  
@terencehonles , I'll take your code from  f2d0288 and make a tiny change.

**Comment by terencehonles** [comment]
sounds good to me

**Comment by pavelgk** [comment]
I'd like to contribute to the manual concerning the vault. I'll create a new PR for that.

**Comment by p12tic** [comment]
I think with the documentation additions by @pavelgk we can close this issue. Thanks a lot for contributing the PR.
