### ISSUE TITLE
txrequests, treq and certifi in the documentation

### ISSUE THREAD

**Issue by vx-i** [buildbot/buildbot#5483]
I would like to improve the buildbot documentation, especially topics belonging to txrequests, treq and certifi. Please don't judge me too harshly. Maybe it's just beginner's thoughts :-)

txrequests and treq are not mentioned in the installation manual, but one of those libs is necessary for Buildbot operation. It would also be good to see the differences of both libs. For example treq do not support proxies.

certifi is working good as long as your http_proxy and https_proxy environment variables are set up. But this is also not clearly mentioned in the documentation. Something like: "If you are behind a proxy, please check ...". Or if you are using your own certificates, you need to extend cacert.pem. By the way, I don't know if it is a good idea, because it will be overwritten with next certifi update. Is there a better solution to set up own certificates, like:

c['secretsProviders'] = [secrets.HashiCorpVaultSecretProvider(
                        vaultToken="mytoken",
                        vaultServer="http**S**://myhostname:8200",
                        **certfile="filename"**
                        secretsmount="kv",
                        apiVersion=2
)]

**Comment by p12tic** [comment]
@vx-i Many thanks for the bug report. It's really useful because each person has only single opportunity to improve documentation - when he goes through it the first time. Once the person knows solutions to the problems, everything is obvious to him and the documentation seems perfect :-)

Would you like to edit the documentation to add all information you think should be there? It's located in rst files in master/docs directory. There's a small section of how to set up local documentation builds here: http://docs.buildbot.net/2.8.0/developer/pull-request.html#local-testing-cheat-sheet (see the generic description and the "documentation" section below).
