### ISSUE TITLE
GerritChangeSource marks comment-added events as duplicated

### ISSUE THREAD

**Issue by gerard** [buildbot/buildbot#5596]
Hi,

We recently upgraded our master from 2.0.0 to 2.8.4.  After the upgrade, all the comment-added gerrit events seem to be classified as duplicated.  This message is being printed when a comment is added (we use gerrit comments to signal CI)

    "gerrit: duplicate change event {} by {}"

Looks like the changes to GerritChangeSourceBase.addChange broke this.  In particular, the stampdict passed to findOrCreateId looks to be missing a few fields for the duplication detection to work correctly.  I suspect that change-merged events have a similar problem, but i didnt check for sure.

As a workaround I reverted the entire gerritchangesource.py to 2.0.0 level, which works for us.

**Comment by p12tic** [comment]
@gerard Thanks for the bug report. Could you explain your use case a little bit? How do you configure the GerritChangeSource? I assume you subclass it and add an additional method for the `comment-added` events which creates builds depending on the comment text. Is it something like this in your setup?

**Comment by gerard** [comment]
There is no subclassing.  I just have "comment-added" in my handled_events array.  My understanding is that this is documented behaviour.

        gerrit_listener = changes.GerritChangeSource(
            gerrit_server,
            gerrit_user,
            handled_events=[
                "patchset-created",
                "ref-updated",
                "change-merged",
                "comment-added"
            ]
        )

**Comment by DisBeGee** [comment]
Hi yes i'm also getting this issue too. I'm about to be away so I don't have time to give details right now, but in terms of replication it occurs when we had legacy code do an addChange call (haven't refactored it but it compiled so assumed it was okay), we triggered a Gerrit patch, it would succeed, we would trigger that same patch again for various reasons (no change to patchset commit hash), and it would not queue up with the following error in twistd:

 gerrit: duplicate change event ssh://buildbot@gerritserver.com:12345/project -- master:49cb...a5df7 by ServerGerritChangeSource

**Comment by p12tic** [comment]
@gerard @DisBeGee Could you please look into #5732 and tell what you think?

What is the likely expectation of a Gerrit user? Does inclusion of `comment-added` event mean that Buildbot should rebuild the commit on each comment?

**Comment by simark** [comment]
Hi,

I just stumbled on this.  Here's my use case:

* I want to make the CI builds from Gerrit manually started. When I am ready for a particular Change to be CI-tested, I want to go to the change and say "please build this".
* The best way I found (inspired from an existing setup that uses Jenkins this way) is to have a `CI-Build` label that I set to `1` to indicate I want to build this change.
* I wrote my own `GerritChangeSource` sub-class to only handle `comment-added` events (which are fired when one sets a label) and add a change when it sees the `CI-Build label` transitioning from 0 to 1.  See code below for reference.
* Sometimes, the CI fails for some reason.  But whatever the reason, it's useful to be able to re-trigger the build, by turning the label back to 0 and then back to 1.
* Since the changes are de-duplicated, the second time you set the label to 1, it's ignored.

While writing this, I remembered that builds have a "Rebuild" button, I'll have to see if that works.  Either way, I think it would be useful for my change source to be able to add some unique field to the source stamp to force it to be unique.

```python
    def eventReceived_comment_added(self, properties, event):
        print(">>> properties:", properties)
        print(">>> event:", event)

        # Check if "CI-Build" went from 0 to 1.
        if "approvals" not in event:
            print('>>> comment-added: "approvals" not in event')
            return

        ci_build_label = None
        for approval in event["approvals"]:
            if "type" in approval and approval["type"] == "CI-Build":
                ci_build_label = approval
                break

        if ci_build_label is None:
            print(">>> comment-added: CI-Build label not found")
            return

        if "value" not in ci_build_label:
            print('>>> comment-added: "value" not in label')
            return

        if ci_build_label["value"] != "1":
            print('>>> comment-added: ci_build_label["value"] is not "1"')
            return

        if "oldValue" not in ci_build_label:
            print('>>> comment-added: "oldValue" not in label')
            return

        if ci_build_label["oldValue"] != "0":
            print('>>> comment-added: ci_build_label["oldValue"] is not "0"')
            return

        print('>>> comment-added: adding change')

        self.addChangeFromEvent({"try": True}, event)
```
