### ISSUE TITLE
Reboot master as build step without failing build

### ISSUE THREAD

**Issue by vx-i** [buildbot/buildbot#5788]
As part of my CI strategy I need to reboot master as last build step. However after master restarts the last build step is marked for retry and master restarts again (dead loop :-)). Here are the build steps:

1. Checkout git
2. if master.cfg is changed, buildbot checkconfig
3. if OK, copy master.cfg to master folder
4. restart master

What do you think about? Does it make sense?

Our master is operating on Windows, so reconfig parameter is not working. Maybe restart is not needed, but how to get rid of reconfig on Windows?

Cheers
Alex

**Comment by tardyp** [comment]
Hello,
Not sure what kind of reason would require to reload the master configuration and restart at the end of the step.
It is indeed tricky due to the automated retry of builds that are running while doing a restart.

What you can do is a clean restart.
a clean restart is waiting for current builds to finish instead of stopping them, and marking them as retry.
actually, the clean option is only available for stop, so you need to do buildbot stop --clean and the buildbot start.

However, if your script is running in a step, it will never end, waiting for the master to stop, which is itself waiting for the script to finish.
So you will have to use some kind of daemonization of your restart script so that it detaches from the build process.

**Comment by vx-i** [comment]
At least our reason is: We keep all our config files in a mono repo. If master.cfg is changed and pushed to repo, Buildbot recognize it, check config file and need to restart master. 

Your idea to stop master is good, but not working:
```
PS D:\Buildbot\master> buildbot.exe stop --clean
buildmaster not running
```
I'm able to monitor Buildbot windows service via Prometheus and after it stops to restart it again.

**Comment by tardyp** [comment]
stop --clean uses unix signals in order to communicate buildbot process the desire of clean shutdown.
I am not sure how the whole thing behave on windows. We highly recommend using unix for master process as this is where it is used the most.

On windows, I guess you will need to dive in the code in order to see why this is not working.

**Comment by vx-i** [comment]
@tardyp What do you think about https://github.com/Pylons/hupper. It supports also Windows platform to restart processes if e.g. config file changes. Is it possible to integrate this lib, or at least to reuse some code snippets like https://github.com/Pylons/hupper/blob/master/src/hupper/winapi.py to send CTRL-C event?

**Comment by sphet** [comment]
We have similar requirements but handle the restart of the master *outside* of the master. We watch the master.cfg file and if it has changed we gracefully shutdown and restart. I believe the script is written in python

**Comment by vx-i** [comment]
Thanks @sphet.
