### ISSUE TITLE
Custom statistics back-end

### ISSUE THREAD

**Issue by sphet** [buildbot/buildbot#5870]
We are thinking about adding Builbot build times to our dashboard, which uses MongoDB for storage. My first thought was to add a final step for each builder which walks the steps and reports the build times to the database. However, I see that the statistics subsystem has already been written to use a third party storage, but that it is the only one available right now. Is there anything preventing me from trying to write our own statistics store and leverage the BB statistics core?

**Comment by tardyp** [comment]
Hi,

The stats backend is pluggable. 
There is only a plugin for influx, but the only thing needed it to implement this method, and to configure it instead of InfluxStorageService

https://github.com/buildbot/buildbot/blob/2b70424f8960b5b0d480589e9d711dea40556562/master/buildbot/statistics/storage_backends/base.py

**Comment by p12tic** [comment]
Looks like the question is answered, isn't it? Please reopen the issue if there are any followup questions.
