### ISSUE TITLE
Rewriting www frontend from AngularJS to React 

### ISSUE THREAD

**Issue by p12tic** [buildbot/buildbot#5875]
This post outlines a rough plan of moving from AngularJs as it will reach end of life in December 2021 (https://docs.angularjs.org/misc/version-support-status).

React has been chosen as the technology we will be moving to due to its popularity and familiarity to the maintainers willing to invest time in the migration effort. Currently the only one willing to put significant amount of effort is me, but if anyone wants to implement the migration then other technology choices may be considered.

The rough plan is as follows:

 - Create www/base_react, www/{component}_react and so on directories that will house the www components rewritten in react.
 - The current www packages are not affected and are released as is until the migration is over.
 - The react www packages are released to pypi and named by appending `-react` to the name of the non-react package. The pypi description says that these packages are temporary and will be updated until React-based implementation becomes default. 
 - On Buildbot 4.0 or 5.0 the React-based www packages become the default, the `-react` temporary packages on pypi are deprecated.

**Comment by p12tic** [comment]
@tardyp what do you think?

**Comment by tardyp** [comment]
I changed a bit my mind on react last year. I made a small project using it and liked it much more than when I tried it first back in 2017.
Most of it is due to react hooks and typescript and FunctionComponent. I found those allow to express very efficiently what is necessary to build UI component.

Now your plan looks good as per migration plan. The UI should not be too difficult to port.

What worries me a bit is the buildbot-data module. Its implementation is very dependent on angular services, and has a number of short coming in its API and in its implementation.
So I think it would make sense to change that API as we switch to react.

One of the shortcomings of the API is the N+1 problem that comes with the REST api.
I have been amazed by the GraphQL API, and I think this would have helped to build the buildbot UI.
What I don't like too much about graphql api is the pub/sub api. I would have liked there is something more automatic.

Ideally we would like to have to say in the component

```graphql
{
    builder (name: $name) {
        id
        name
        build(number: $number) {
             buildsteps {
                  name
                  status
                  logs {
                     name
                  }
             }
       }
}
```
and the buildbot-data would just update automatically when the underlying data updates.
Obviously this cannot be implemented fully client side.
Actually, probably most of the implementation should be server side. This is a huge work, and I haven't found open-source framework that would really make it easy to implement on top of our current data + mq apis.

**Comment by tardyp** [comment]
https://ariadnegraphql.org/ wasn't available last time I checked, and look more suitable for what I had in mind

**Comment by p12tic** [comment]
For initial switch to React I would like the amount of changes al low as possible. The migration will take a lot of time anyway, so it's better not to expand the effort needed even more.

**Comment by tardyp** [comment]
I agree, that this is a big job. My point/experience is that it will be much easier if we have a stronger state management story. This can be done independently, as this would be a v3/ api.
At $work, due to crisis, I will be on partial unemployment on Fridays, April to august. So I might have some time to help on it.

**Comment by terencehonles** [comment]
Does it not make sense to try to move to Angular? Angular supports wrapping AngularJS while migrating and that might make things easier. It really depends where you want the final destination to be.

One thing that I noticed when working on www is that it uses jade as a templating language and I believe I saw you can drop in your own templates. Is that something that still needs to be supported?

I'm not sure how that might work for react and I'm not sure how well Angular would play with that either. It seems the shift with Angular is to move to AoT compilation and it's compiler handles the whole thing which would mean that in order to allow overriding templates the application would need to be split into libraries / building blocks which others could consume / style. If that can be dropped then the transition would be simpler regardless.

I might have some cycles to help with this, and I do have experience with Angular (I've also used react, but not professionally and also a while ago now).

**Comment by terencehonles** [comment]
If you're not familiar with the upgrade story for Angular it's here https://angular.io/guide/upgrade and I'm referring specifically to https://angular.io/guide/upgrade#upgrading-with-ngupgrade

**Comment by p12tic** [comment]
The primary reason to use React is that it's most popular framework ([Google trends](https://trends.google.com/trends/explore?date=all&geo=US&q=%2Fg%2F11c6w0ddw9,%2Fm%2F0j45p7w,%2Fm%2F012l1vxv,%2Fg%2F11c0vmgx5d)) so it reduces the barrier for new contributors on average. All technical merits are a secondary priority as we have not been hitting any bottlenecks on the www frontend so far.

> One thing that I noticed when working on www is that it uses jade as a templating language and I believe I saw you can drop in your own templates. Is that something that still needs to be supported?

I think anything is on the table depending on technical feasibility. Enabling arbitrary customizations has the downside that the effective surface of the "API" provided by Buildbot frontend becomes very large and then it's hard to preserve backwards compatibility. It's relatively easy to build Buildbot from source, we can provide better step-by-step instructions and just tell people that they can do whatever they want, but their setup can break at any time.

The API of www plugins will remain in any case and given that it's very small API it will be easy to support it whatever framework we choose.

**Comment by terencehonles** [comment]
Well they are both pretty popular from that graph and if you narrow it to just a year it looks like React has dropped more than Angular so they are closer together. 

![Screenshot from 2021-03-31 18-09-30](https://user-images.githubusercontent.com/438813/113229654-42c04a00-924c-11eb-9092-8ccb711db9d6.png)

I'm mainly suggesting it because I assume this will take some time to rewrite and Angular has an interoperability strategy. If you'd prefer to rewrite in one go and you'd prefer React then that's fine, but not how I imagined this might proceed.

**Comment by tardyp** [comment]
as @rodrigc pointed out on IRC, protractor is also sunsetting.  

> From https://github.com/angular/protractor/issues/5502 , it looks like the Protractor e2e test framework is deprecated and will be sunsetted in 2022

**Comment by p12tic** [comment]
Addressed in https://github.com/buildbot/buildbot/pull/6664. Current version is only the base package, implementation for plugins will come later.
