### ISSUE TITLE
Regression: Owners column empty for pending build-requests

### ISSUE THREAD

**Issue by aj062** [buildbot/buildbot#5940]
Owners column is empty for pending build-requests in Buildbot 2.10.2. This used to work properly in Buildbot 1.8.2

This issue can also be noticed at https://buildbot.buildbot.net/#/builders/3
<img width="607" alt="empty_owners_column_pending_buildrequests" src="https://user-images.githubusercontent.com/3098702/112046835-e6aa4700-8b22-11eb-83d1-b848a16b6e04.png">

**Comment by tardyp** [comment]
this is due to owners property not being present in the buildrequest (anymore?)

**Comment by tardyp** [comment]
I don't see any diff since 1.8.2 that would remove this property in buildrequests
There is an old issue about it, but I am not even sure this was properly verified to be fixed
https://github.com/buildbot/buildbot/issues/4207

pending buildrequest is quite rare. actually in metabuildbot, this was a bug in our master.cfg that prevented builds to start.

**Comment by aj062** [comment]
This was working fine in v2.1.0, but stopped working in v2.2.0

Seems to be a regression due to https://github.com/buildbot/buildbot/commit/ee1f853360b1016f3ed28489b179f7af2e2986c2

**Comment by aj062** [comment]
Verified that reverting https://github.com/buildbot/buildbot/commit/ee1f853360b1016f3ed28489b179f7af2e2986c2 and recompiling buildbot-www package fixes this issue.
