### ISSUE TITLE
Question: Easiest way to share a hardware pool across multiple buildbot masters, with locking?

### ISSUE THREAD

**Issue by alex-nl** [buildbot/buildbot#6127]
Currently we build multiple projects using Buildbot, and each of those has a separate master and pool of workers, running on our own hardware. This is specialized hardware (we can't replace it with cloud VMs) and there are non-negotiable reasons why we can't merge these projects under a single Buildbot master. As such, currently each project has its own pool of machines, and each machine only runs builds for one project. As different projects build at different rates, this is giving us poor utilization of our hardware pool. 

I'd like to change this. Essentially, I want a single machine to be able run workers for multiple projects, with some machine level locking. That is, I can run multiple workers for multiple projects on a single machine currently, but I want a worker for Project A to reject builds if a worker for Project B is actively building something.

I'm happy to write new code here that's custom to my use case, but I'd like some pointers on how to manage the interactions with buildbot. Perhaps I could subclass some of the Worker code to allow interacting with a custom system-level locking mechanism? Or perhaps a new Latent Worker implementation that fails to spin up if the underlying hardware is already in use? 

Apologies for the open ended question, but any suggestions would be much appreciated. Thank you!

**Comment by p12tic** [comment]
I think the feature for sharing workers between masters makes sense in principle, but it would require some serious refactoring on Buildbot side.

As an interim solution, I think you could create a pair of steps for every builder - one that would lock a worker and another that would unlock. As a result you could just run multiple Buildbot workers connecting to different masters on the same hardware. This approach unfortunately would have reliability issues as in case of worker disconnection the unlock step may not be called. You could handle this case with some custom code on the buildbot-worker package.

**Comment by tardyp** [comment]
I think the best way to do this is to use the LatentWorker framework.

a LatentWorker is a controller on the master which will start the worker remotely using a protocol of many mean.

So you can just create a new LatentWorker implementation, that can just ssh to a worker, take a lock and start the correct worker that will connect to the right master.
Like for the other proposal from @p12tic they key will be lock contention, how to make sure that the lock is correctly released when the worker are done.

Maybe you need a worker manager process similar to supervisord which would monitor the worker processes and make sure there is only one.

Then if the lock is already taken, the LatentWorker will "fail to substantiate", and trigger the generic method in the master, which will quarantine that worker for a little while, and retry with another worker.

A bottleneck of this method is that for every failed substanciation, the master will record a new build, so in case of heavy load, there will be lot of useless builds.

also the LatentWorker only does polling retry with exponential backoff timer (backed by the quarantine timer), so there builld will not be started on the other master right after the previous build finished. You could tweak a bit the quarantine timer so that the maximum delay is not too big.
 
Also, you do not give much info on your actual worker setup. Is this windows/linux, what kind of special setup is attached to it?

If you have some kubernetes expertise in the team, then using the kubeLatentWorker might help. you can just use the kubernetes ressource requests to make sure only one worker runs per node. you can also use node affinity to redirect your pods to a particular node.

in any case this is a fun but hairy challenge you got :)

**Comment by alex-nl** [comment]
Thank you both for the insightful suggestions!

To give a bit more context, we have a variety of post-build steps, many of which have a very specific hardware requirements (different drivers, attached devices, operating systems, memory requirements, etc). Our hardware pool is relatively static and the different types of machines are not interchangeable. I think for now Latent Workers might not be the easiest approach, as I'd have to implement a worker manager process that can handle the variance in our hardware requirements. I'm interested in this going forward, but for now I'd like to see if I can quickly hack something together, using custom code in the buildbot-worker package. 

Could I get some code pointers for the buildbot-worker package? Ideally I could hack something such that that whenever a worker connects or reconnects to a master in order to carry out a build step, I could run some custom locking code.

**Comment by p12tic** [comment]
Quickest would be:
 - Add a step that runs lock command at the beginning of each build. This way you will be able to utilize all the existing infrastructure around steps with regards to timeouts and so on. If you just do waiting somewhere else, you will likely hit edge cases because e.g. Buildbot does not expect a build not to start for two hours.
 - Add a step that is always ran (see `alwaysRun=True`) at the end of the build. This one should run the unlock command.
 - Add code to find and clear stale locks for the current master in `BotBase.remote_shutdown`, `AutoLoginPBFactory.gotPerspective`, `AutoLoginPBFactory.failedToGetPerspective` and `BotFactory.waitForCompleteShutdown`. The first will clear locks when the worker is stopped from the master side, the next two will clear locks when worker attempts to reconnect e.g. after dropped connection and the last one will clear locks when the worker is about to finish shutting down.

The above should be relatively resilient to various kinds of failures, but I don't guarantee I didn't miss something :-)

**Comment by alex-nl** [comment]
Brilliant, thanks.
