### ISSUE TITLE
QUESTION: WAMP connection problems?

### ISSUE THREAD

**Issue by rvanlaar** [buildbot/buildbot#6131]
We're running a multiMaster buildbot. 2 masters with local workers and one for the UI
We've been getting random unrecoverable errors since using crossbar.

We've set crossbar to level trace, but it didn't show any errors.

This is from our the ui master:

```
2021-07-05 19:30:22+0000 [-] BuildMaster is running
2021-07-05 19:30:39+0000 [-] Unhandled error in Deferred:
2021-07-05 19:30:39+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
            result = current_context.run(g.send, result)
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/buildbot/www/ws.py", line 116, in cmd_stopConsuming
            yield qref.stopConsuming()
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1656, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1571, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/buildbot/www/ws.py", line 116, in cmd_stopConsuming
            yield qref.stopConsuming()
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
            result = current_context.run(g.send, result)
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/buildbot/mq/wamp.py", line 107, in stopConsuming
            yield unreg.unsubscribe()
          File "/home/director-buildbot/.cache/pypoetry/virtualenvs/buildbot-director-RW1KhLrq-py3.8/lib/python3.8/site-packages/autobahn/wamp/request.py", line 103, in unsubscribe
            raise Exception("subscription no longer active")
        builtins.Exception: subscription no longer active
```
What can we do to resolve this?

**Comment by rvanlaar** [comment]
On further investigation, we're getting these errors in crossbar:

```2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.protocol.WampWebSocketServerProtocol] Connection to/from tcp4:127.0.0.1:54958 was closed cleanly
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.protocol.WampWebSocketServerProtocol] _connectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
]
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.protocol.WampWebSocketServerProtocol] Auto ping/pong: canceling autoPingPendingCall upon lost connection
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.protocol.WampWebSocketServerProtocol] WAMP-over-WebSocket transport lost: wasClean=False, code=1006, reason="connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)"
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.session.RouterSession] RouterSession.onClose(was_clean=False)
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.service.RouterServiceAgent] RouterServiceAgent.publish("wamp.session.on_stats") -> "wamp.session.on_stats" on "realm1"
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.router.Router] session "797439264882512" left realm "realm1"
2021-07-05T20:46:47+0000 [Router       1843 crossbar.router.router.Router] 
SessionDetails(realm="realm1",
               session=797439264882512,
               authid="JTPN-P4F7-KUW6-T6KR-LQK4-QNU7",
               authrole="anonymous",
               authmethod="anonymous",
               authprovider="static",
               authextra={'x_cb_node': 'john.scummvm.net-1801', 'x_cb_worker': 'worker001', 'x_cb_peer': 'tcp4:127.0.0.1:54958', 'x_cb_pid': 1843},
               serializer=None,
               transport=None,
               resumed=None,
               resumable=None,
               resume_token=None)
```

**Comment by tardyp** [comment]
Hello. It sounds like you may have connectivity issue with you wamp server.

could that be a reverse proxy timeouting?

**Comment by rvanlaar** [comment]
Hi @tardyp Thank you for thinking in solutions.

It's running locally, with the default `crossbar init` settings.  So no reverse proxy. 
The system though is under high load when running builds.

**Comment by rvanlaar** [comment]
As far as debugging goes, the problem went away when we configured crossbar to not send pings: 
`"auto_ping_interval": 0,`

**Comment by tardyp** [comment]
mmh, its possibly removing the symptom, not the problem. You might still be loosing data without knowing.

f the machine is overloaded, maybe separating postgres + wamp out of the build master would be a wise idea.

Regards

**Comment by rvanlaar** [comment]
Thank you for the feedback.

The server in use does has multiple CPUs and one build would eat 100% of one core on the master.  The reason to start using WAMP is to use multiple masters to reduce the load.

Our test system is currently at 2 masters for workers and one for the UI. With both worker masters using between 70 and 90% cpu of one core. 

I tried searching for buildbot and twisted to use more than one core. It seems however single threaded. Is that correct?

**Comment by rvanlaar** [comment]
We've think we've figured it out. It's due to an intensive rest call to /changes/.

We've never had a successful build, which leads to /changes/ returning more a set of more than 17K entries, i.e. a 20MB json file. It would take more than 2 minutes of 100% cpu time to get all the changes.
Timeouts are in the order of seconds. So it makes perfect sense that it wouldn't respond in a timely matter.
See for example this build result: https://john.scummvm.org/#/builders/18/builds/1019

For us, we would only need to see the last 100 changes at maximum.

Buildbot is quite configurable with interfaces and such.

Is there a way to get to replace just the data.changes:ChangeEndpoint class or the db.changes:ChangesConnectorComponent class?

**Comment by tardyp** [comment]
An overlook in the design of the REST api is that indeed, it is not limitted by default.
However, most of the official users of the rest api will actually use the limit='xx' rest api argument.
e.g:

https://john.scummvm.org/api/v2/changes?limit=100

I am not sure why having only failed build is related to your issue, though.
Do you have a script that would use unlimited rest api?

**Comment by rvanlaar** [comment]
Thank you @tardyp  that's a much appreciated response.

> However, most of the official users of the rest api will actually use the limit='xx' rest api argument.

The request for changes is done by the angular front-end that comes with buildbot.
Loading this page: https://john.scummvm.org/#/builders/18/builds/1019
results in a request on: https://john.scummvm.org/api/v2/builds/21422/changes

The  `?limit=1` doesn't seem to work. Compare these two examples from buildbot.buildbot.net:

```
$ curl "https://buildbot.buildbot.net/api/v2/builds/92692/changes"|grep total
    "total": 2
```
```
$ curl "https://buildbot.buildbot.net/api/v2/builds/92692/changes?limit=1"|grep total
    "total": 2
    ```
It seems to me there are two separate points:
 - limit=XX is not respected on the builds/n:buildid/changes
     i.e. fieldMapping is only set when requesting /changes without buildid or ssid
 - angular front-end requests all changes

**Comment by tardyp** [comment]
ah. So it is a bit different, and I now understand why the no success full build is important.

Indeed, the buildbot build changes are a different api, which gives the list of changes that may be responsible for the build failure.
It is assume that builds are supposed to be mostly success, but when a post commit build starts to fail, we cannot know which change is responsible from the actual failure.
Because the fixing change might introduce another failure or there might be another failure introduced since the first failure.

So I would suggest to change some our your steps to warn on failure in order to have your technical debt excluded from the failure criteria, and you start having your failure state monitor your actual regressions.

For your other remarks, the limit and field mappings are implemented generically at the higher level of the rest api.
In order to optimize some performance critical queries, they can be implemented at data api level or at db api.

in our case, we could transmit the resultSpec in db api's [getChangesForBuild](https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/changes.py#L172) like we do in [getChanges](https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/changes.py#248)

last, in the json answer, the total argument is always set to the total unlimitted number of answer the query may have answered, but if you actually open the json file, you will see that the data is limited.

In the case of the getChangeByBuilds, however, this limiting is done at the rest API level, so that internally all the changes are fetched from db, and then filtered. So most of computation needed in db level is wasted.

**Comment by rvanlaar** [comment]
Aha, I see. That's why the time to execute the request didn't change. 

I found the changeHorizon parameter in changes.py I've set it to 1000, a 2 week horizon for us. That got the time to request the /changes for a build down to around 7 seconds.

Re: warn on failure.
Our buildbot is used as compatibility test suite. The end goal is to get all the tests to pass.
I made a custom reporter that reports based on changed steps. So we are notified of regressions.

**Comment by tardyp** [comment]
I don't know how the scummvm test suite is written, but usually, known failure are marked in test suite as [expectedFailure](https://docs.python.org/3/library/unittest.html#unittest.expectedFailure)
This allow to have the test suite always green and still track the failures.

When you merge a fix for a compat test, you just need to also merge removal of expectedFailure decorator.
pytest can mix that with parametrize which may be even better for compatibility test suite
https://docs.pytest.org/en/latest/how-to/skipping.html#skip-xfail-with-parametrize

changeHorizon is a good workaround anyway. 

Maybe you should close this issue as eventually we did derive a lot in this debug out of WAMP issue.

I guess the WAMP issue is related from some ping timeouts from or to wamp server which was due to reactor stall because of those long queries.

**Comment by rvanlaar** [comment]
Let's close the issue.

- I'll further look into how buildbot can handle expected failures. For now there's no easy way to achieve this.
- changeHorizon is not mentioned in the domentatation.

To summarize for others:
- got errors after switching to using WAMP: `builtins.Exception: subscription no longer active`
- had an overloaded buildbot, due to builds but also due to the web ui requesting all changes for a build, which also caused 100% cpu load

Resolved it by:
- setting "auto_ping_interval": 0, in the crossbar config
- setting c["changeHorizon"] to 1000, (keeps only the last 1000 commits)
- created a multiMaster setup: 2x UI and 2x builders.
