### ISSUE TITLE
The problem of displaying the current time incorrectly when we do not reconfig

### ISSUE THREAD

**Issue by ardakoc** [buildbot/buildbot#6825]
When we want to get the current datetime in the build steps, it always returns the same datetime (the datetime of last reconfig) until we do the reconfig. For this, we tried the datetime.datetime.now(), time.localtime() and buildbot.util.now() methods and got the same result in all of them. You can review a sample code snippet we used below:

```
from time import localtime, strftime
from buildbot.process.properties import WithProperties
from buildbot.steps.shell import SetPropertyFromCommand

...

SetPropertyFromCommand(
    command=[
        '/bin/mkdir',
        '--verbose',
        WithProperties('{}'.format(strftime("%Y%m%d-%H%M", localtime()))),
    ],
    extract_fn=...,
    ...
)

...
```

Is there a way to update the current datetime during build or constantly update it in the background when the buildbot is running? Or is there something we're doing wrong?

**Comment by vibbo** [comment]
Hi.

What you are doing, when using `.format`, is in fact just generating string **at start/reconfig** time. That's why it does not change.

Please look at https://docs.buildbot.net/current/manual/configuration/properties.html?highlight=withproperties#custom-renderables. There are examples of `util.Interpolate` (non-deprecated version of `util.WithProperties`) using renderable to get current time.

Cheers
