### ISSUE TITLE
Buildset string properties become escaped when triggering a rebuild or if triggered after a buildrequest's build was retried

### ISSUE THREAD

**Issue by ArthurPKFX** [buildbot/buildbot#6898]
This is caused by the db call from `BuildsetsConnectorComponent.getBuildsetProperties` (in `db/buildsets.py`) which apparently escapes the string. I checked and the string is correctly stored in the db, unescaped. But when it is retrieved, something somewhere escapes the string
This is a pretty big issue for me, I rely on the formatting of the strings and builds just sometimes fail which retries them and escapes those strings
There is also no easy or clean fix, I would have to check if the current build is not the first one of a buildrequest, and unescape the string multiple times depending on the number of the build. This also doesn't solve the issue with rebuilding
Is this possible to be fixed?

**Comment by mokibit** [comment]
Hi, @ArthurPKFX,
I am trying to reproduce this bug but without much success. 
Which Buildbot version are you using? Which exact characters cause a problem?

**Comment by ArthurPKFX** [comment]
Hi mokibit. We were using 3.4.1 and this persists with 3.7.0. Sqlalchemy was 1.4.32. Newlines and tabs get escaped for sure, I don't think I've tested more than that

**Comment by mokibit** [comment]
Hi, @ArthurPKFX.

While trying to reproduce your problem:
1) I added a step (through steps.Trigger()), which triggers a build of a builder of interest and sets the buildset string properties being tested (string with '\n' and '\t' characters)
2) Rebuilt the build with properties mentioned above with "Rebuild" button in Buildbot UI
3) Logged BuildsetsConnectorComponent.getBuildsetProperties() string properties (received from the database) and made sure that the strings indeed contain the special characters (by calling `.encode('utf-8').hex()`)

Results:
1) Database has string properties escaped: with '\n' and '\t' (`0x5c 0x6e` and `0x5c 0x74` in hex) for both original and rebuilt buildsets
2) `master.db.buildsets.getBuildsetProperties()` gets string properties unescaped: with raw '\n' and '\t' (`0x0a` and `0x09` in hex) for both original and rebuilt buildsets

Could it be that you printed `\n` and assumed that it was escaped (e.g. `print("\n")` will print newline character, but `print(["\n"])` will print `['\n']`)?

If not, could you provide more information about your problem? What exact data does the database have? How are you deciding that the properties are wrongly escaped? It would be great to have a redacted copy-paste or screenshot so that potential of errors in our communication is reduced.

**Comment by ArthurPKFX** [comment]
As a quick reply, specifically the property that gets escaped in our case is a parameter, which is filled in a network request and is then escaped when rebuilding, in case that changes anything. I don't see how it would when looking at the internal code though
I am certain that the string gets escaped, however. It shows as such in the properties section of the build in the buildbot UI, as well as in the DB. The amount of escaping also grows with each rebuild, making it even more obvious

I will gather more data on our issue and try to make a repro case when I have some time. Thanks for looking into this :)

**Comment by p12tic** [comment]
I will close this bug for the moment. Please reopen when there is more details on how to reproduce the issue.

**Comment by ArthurPKFX** [comment]
Fair enough 🙂 I was actually working on this the day before yesterday. I have a repro in my project but once I extracted it into a standalone project it didn't work anymore. I need to check all the possible differences between the two, it's really weird

**Comment by ArthurPKFX** [comment]
Raising this back from the dead as I was able to look a bit into it and the answer hit me: I was using the json optimization from https://docs.buildbot.net/3.11.0/manual/optimization.html
Disabling this resulted in no more escaping issues

Replacing `list(m.groups())` with `[group.encode('latin-1', 'backslashreplace').decode('unicode-escape') for group in m.groups()]` fixes the escaping issue for my case but the performance becomes worse than the proper JSON parser. So I'll disable this optimisation in my project. This might warrant a mention in the documentation however
