### ISSUE TITLE
buildbot-badges doesn't work with the new react frontend

### ISSUE THREAD

**Issue by JulienMalka** [buildbot/buildbot#7665]
Is a new react-badges plugin on the roadmap ?

**Comment by p12tic** [comment]
Thanks for noticing this problem, now it is on the roadmap.

**Comment by tdesveaux** [comment]
From what I could see, the  plugin still works, however it's (and all other non-ui plugins) initialization it broken.

On startup, the master call [`WWWService.configPlugins`](https://github.com/buildbot/buildbot/blob/c17d1aac27999eaf39926e3b30070ebd2f346110/master/buildbot/www/service.py#L284) twice. First from [`setupSite`](https://github.com/buildbot/buildbot/blob/c17d1aac27999eaf39926e3b30070ebd2f346110/master/buildbot/www/service.py#L322), then a second from [`reconfig`](https://github.com/buildbot/buildbot/blob/c17d1aac27999eaf39926e3b30070ebd2f346110/master/buildbot/www/service.py#L391).

In reconfig, the configuration for non-ui plugins is [removed from the config](https://github.com/buildbot/buildbot/blob/c17d1aac27999eaf39926e3b30070ebd2f346110/master/buildbot/www/service.py#L307-L308) (no-idea why, introduced in [this commit](https://github.com/buildbot/buildbot/pull/3744/commits/914798f19475b5eac51a56cffea0901dec8f5765) but no comments on why) so the second call will not initialize the badge plugin (and other non-ui, since they are 'not configured').

It worked before as plugins were added to the root resource directly, so unless they were overridden by another plugin with the same key, they stayed. However, with the react rewrite, plugins were moved to a [`/plugins/`](https://github.com/buildbot/buildbot/blob/c17d1aac27999eaf39926e3b30070ebd2f346110/master/buildbot/www/service.py#L295) resource, which is recreated at reconfig.

This lead the reconfig to re-create a new `plugins` resource, but since the non-ui plugins are no longer in the config, they are not added, thus not available.

I can see two options here:
- leaving non-ui plugins in conf
- retrieving the `plugins` resource (with `root.getStaticEntity(b"plugins")`), creating a new one only if not present (this mean reconfig can't remove plugins).

**Comment by p12tic** [comment]
Looks like "leaving non-ui plugins in conf" is better option.

Thanks for looking into this.
