### ISSUE TITLE
Buildbot 4.0.2 has broken docker-py version check

### ISSUE THREAD

**Issue by cmouse** [buildbot/buildbot#7915]
Line https://github.com/buildbot/buildbot/blob/44928c0a0189efc6ff4aedc4926a0c92ad086644/master/buildbot/worker/docker.py#L151 seems not to work with docker-py 7.1.0, which is compatible with buildbot. The version detection does not seem to work. Removing this check enables buildbot to work though.

Buildbot version 4.0.2

**Comment by mokibit** [comment]
Hi, @cmouse,
Thanks for opening an issue.
I tested Buildbot (both master version and 4.0.x) and Python itself. 
For me output seems to be correct: 
`docker.__version__ ` being 7.0.0 or 7.1.0, 
comparison of docker version with result of parse("4.0.0") in the relevant line is False (works as expected).

Could you print `docker_py_version` and its comparison with  parse_version("4.0.0") in your system:

**Comment by mokibit** [comment]
Hi @cmouse,
Thanks for opening an issue.
I ran the code on Buildbot (both master and version 4.0.x) and Python alone. 
It seems to work with expected values:
`docker_py_version`: 7.0.0 and 7.1.0, and result of `parse_version("4.0.0")` compared with docker version equals to False (as expected).

Could you print the relevant variables in your system (outside of the class DockerLatentWorker), to see what causes the problem? Example:
print("docker_py_version = ", docker_py_version)
print("parse_version 4 = ", parse_version("4.0.0"))
print(docker_py_version < parse_version("4.0.0"))

**Comment by p12tic** [comment]
Assuming @mokibit did the tests right, seems like this could be issue in the user environment, not Buildbot. The code seems to be so simple it's unlikely it just broke. 

I'm thus closing the issue, please reopen if it occurs again and debugging information can be supplied.

Thanks for the bug report anyway, it's important to have it open so that other affected users could chime in. It's easier to write a comment compared to full bug report.
